<?php

  function covertMeta($in) {
     $search  = array('<z>', '<m>', '<s>', '<s1>', '<a>', '<amc>', '<am>', '<q>',       '<cmdl>',                                                      '<gpc>',                                         '<d>', '<ax>',              '<ava>', '<spa>', '<fun>'            ,'<sme>', '<qq>');
     $replace = array('\b', '*',   '\s*', '\s+',  '.+?', '[a-zA-Z0-9_]+?', '.*?',  '[\'"]{0,1}',     '(system|shell_exec|passthru|popen|proc_open)', '(GET|POST|SERVER|COOKIE|REQUEST)', '\d+', '[a-z_0-9\(\)\s]+?', '[a-zA-Z_0-9]+', '\|', '[\'"\(\$]'  , '{2,15}', '[\'"]');
  

     for ($i = 0; $i < count($in); $i++) {
          $in[$i] = str_replace('|', '<spa>', $in[$i]);
          $in[$i] = str_replace($search, $replace, quotemeta($in[$i]));
     }

     return $in;
  }

  $g_DBShe[] = 'MrHazem';
  $g_DBShe[] = 'K!LL3r';
  $g_DBShe[] = 'Dr.abolalh';
  $g_DBShe[] = 'pVxbj+LYtf4rQT/MR';
  $g_DBShe[] = '$rand_writable_folder_fullpath';
  $g_DBShe[] = '$info .= (($perms & 0x0040) ?(($perms & 0x0800) ? \'s\' : \'x\' ) :(($perms & 0x0800) ? \'S\' : \'-\')';
  $g_DBShe[] = '<textarea name=\"phpev\" rows=\"5\" cols=\"150\">".@$_POST[\'phpev\']."</textarea><br>';
  $g_DBShe[] = '7TMGAHY5KaM9o37W/GQ/frFJetfqlRGO6FSRTMm7ILSm35o5z4+v0mcf4KaHgKS5Y17eqqvD2mmN8NzteyplNd6WOwrQVK445J/y0';
  $g_DBShe[] = 'c99ftpbrutecheck';
  $g_DBShe[] = 'By Psych0';
  $g_DBShe[] = 'c99shell';
  $g_DBShe[] = 'r57shell';
  $g_DBShe[] = '$c99sh_updatefurl';
  $g_DBShe[] = 'temp_r57_table';
  $g_DBShe[] = 'admin@spygrup.org';
  $g_DBShe[] = 'R0lGODlhJgAWAIAAAAAAAP///yH5BAUUAAEALAAAAAAmABYAAAIvjI+py+0PF4i0gVvzuVxXDnoQ';
  $g_DBShe[] = 'casus15';
  $g_DBShe[] = 'WSCRIPT.SHELL';
  $g_DBShe[] = 'Executed command: <b><font color=#dcdcdc>[$cmd]';
  $g_DBShe[] = 'ctshell.php';
  $g_DBShe[] = 'BDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAQABADASIAAhEBA';
  $g_DBShe[] = '[Av4bfCYCS,xKWk$+TkUS,xnGdAx[O';
  $g_DBShe[] = 'DX_Header_drawn';
  $g_DBShe[] = '9tZSB0byByNTcgc2hlbGwgJiYgL2Jpbi9iYXNoIC1pIik7DQogICBlbHNlDQogICBmcHJpbnRmKHN0ZGVyciwiU29ycnkiKTsNCiAgIGNs';
  $g_DBShe[] = 'crlf.\'unlink($name);\'.$crlf.\'rename("~".$name, $name);\'.$crlf.\'unlink("grp_repair.php"';
  $g_DBShe[] = '/0tVSG/Suv0Ur/haUYAdn3jMQwbbocGffAeC29BN9tmBiJdV1lk+jYDU92C94jdtDif+xOYjG6CLhx31Uo9x9/eAWgsBK60kK2mLwqzqd';
  $g_DBShe[] = 'mpty($_POST[\'ur\'])) $mode |= 0400; if (!empty($_POST[\'uw\'])) $mode |= 0200; if (!empty($_POST[\'ux\'])) $mode |= 0100';
  $g_DBShe[] = 'WT+P{~EW0ErPOtnU@#@&^l^sP1ldny@#@&nsk+r0,GT+';
  $g_DBShe[] = 'klasvayv.asp?yenidosya=<%=aktifklas%>';
  $g_DBShe[] = 'nt)(disk_total_space(getcwd())/(1024*1024)) . "Mb " . "Free space " . (int)(disk_free_space(getcwd())/(1024*1024)) . "Mb <';
  $g_DBShe[] = 's().g().s().s().g().s().s().g()';
  $g_DBShe[] = 'CRbskEIS+ybKAwc6/OB1jU8Y0YIMVUhxhaOIsHACByD0wMANOHqY5Y48guiBnChkwPYNTkxdBRVRZLHFkojY96II';
  $g_DBShe[] = 'IyEvdXNyL2Jpbi9wZXJsDQokU0hFTEw9Ii9iaW4vYmFzaCAtaSI7DQp';
  $g_DBShe[] = 'CB2aTZpIDEwMjQtDQojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KI3JlcXVp';
  $g_DBShe[] = 'NTDaddy';
  $g_DBShe[] = 'a href="<?echo "$fistik.php?dizin=$dizin/../"?>" style="text-decoration: non';
  $g_DBShe[] = 'TRUFERFIsMSk7DQpiaW5kKFMsc29ja2FkZHJfaW4oJExJU1RFTl9QT1JULElOQUREUl9BTlkpKSB8fCBkaWUgIkNhbnQgb3BlbiBwb3J0XG4iOw0KbG';
  $g_DBShe[] = 'RootShell!\');self.location.href=\'http:';
  $g_DBShe[] = 'm91dCwgJGVvdXQpOw0Kc2VsZWN0KCRyb3V0ID0gJHJpbiwgdW5kZWYsICRlb3V0ID0gJHJpbiwgMTIwKTsNCmlmICghJHJvdXQgICYmICAhJGVvdX';
  $g_DBShe[] = '<%=Request.ServerVariables("script_name")%>?FolderPath=<%=Server.URLPathEncode(Folder.Driv';
  $g_DBShe[] = 'R0lGODlhFAAUAKIAAAAAAP///93d3cDAwIaGhgQEBP///wAAACH5BAEAAAYALAAAAAAUABQAA';
  $g_DBShe[] = 'print((is_readable($f) && is_writeable($f))?"<tr><td>".w(1).b("R".w(1).font(\'red\',\'RW\',3)).w(1):(((is_readable($f))?"<tr><td>".w(1).b("R").w(4):"").((is_writabl';
  $g_DBShe[] = '(\'"\',\'&quot;\',$fn)).\'";document.list.submit();\\\'>\'.htmlspecialchars(strlen($fn)>format?substr($fn,0,format-3).\'...\':$fn).\'</a>\'.str_repeat(\' \',format-strlen($fn)';
  $g_DBShe[] = 'zehirhacker';
  $g_DBShe[] = 'J@!Vr@*&RHRw~JLw.G|xlhnLJ~?1.bwObxbP|!V';
  $g_DBShe[] = 'cihshell';
  $g_DBShe[] = 'X1NFU1NJT05bJ3R4dGF1dGhpbiddID0gdHJ1ZTsNCiAgICBpZiAoJF9QT1NUWydybSddKSB7DQogICAgICBzZXRjb29raWUoJ3R4dGF1dGhfJy4kcm1ncm91cCwgbW';
  $g_DBShe[] = 'JHZpc2l0Y291bnQgPSAkSFRUUF9DT09LSUVfVkFSU1sidmlzaXRzIl07IGlmK';
  $g_DBShe[] = 'Fxc99sh';
  $g_DBShe[] = 'WSOsetcookie(md5($_SERVER[\'HTTP_HOST\'])';
  $g_DBShe[] = 'CQboGl7f+xcAyUysxb5mKS6kAWsnRLdS+sKgGoZWdswLFJZV8tVzXsq+meSPHMxTI3nSUB4fJ2vR3r3OnvXtNAqN6wn/DtTTi+Cu1UOJwNL';
  $g_DBShe[] = '</td><td id=fa>[ <a title=\"Home: \'".htmlspecialchars(str_replace("\\", $sep, getcwd()))."\'.\" id=fa href=\"javascript:ViewDir(\'".rawurlencode';
  $g_DBShe[] = 'Content-Type: $_';
  $g_DBShe[] = '<nobr><b>$cdir$cfile</b> (".$file["size_str"].")</nobr></td></tr><form name=curr_file>';
  $g_DBShe[] = 'wsoEx(\'tar cfzv \' . escapeshellarg($_POST[\'p2\'])';
  $g_DBShe[] = 'eval(base64_decode($_';
  $g_DBShe[] = '5jb20iKW9yIHN0cmlzdHIoJHJlZmVyZXIsImFwb3J0Iikgb3Igc3RyaXN0cigkcmVmZXJlciwibmlnbWEiKSBvciBzdHJpc3RyKCRyZWZlcmVyLCJ3ZWJhbHRhIikgb3Igc3RyaXN0cigk';
  $g_DBShe[] = 'LS0gRHVtcDNkIGJ5IFBpcnVsaW4uUEhQIFdlYnNoM2xsIHYxLjAgYzBkZWQgYnkgcjBkcjEgOkw=';
  $g_DBShe[] = 'if (ereg(\'^[[:blank:]]*cd[[:blank:]]+([^;]+)$\', $command, $regs))';
  $g_DBShe[] = 'vzv6d+iOvtkd38TlHu8mQavXdnJCbpQcpXhNbbLmZOqMopDZeNalb+VKledhCjpVAMQSQnxVIECQAfLu5KgLmwB6ehQQGNSBYjpg9g5GdBihXo';
  $g_DBShe[] = 'round(0+9830.4+9830.4+9830.4+9830.4+9830.4))==';
  $g_DBShe[] = 'PHPSHELL.PHP';
  $g_DBShe[] = 'qhDTZIpMcB1xBok332BjccfPXq0QsZU/g4eapBxT5git1rGdKtwf1rt9OOicc/hTlpeFmEjRRkWGWTJTkCol0X4AuwJSfFhtfP5dOgn561il+wkzkqCG9dfT9zqc274';
  $g_DBShe[] = 'TsNCiAgICBzaW4uc2luX2ZhbWlseSA9IEFGX0lORVQ7DQogICAgc2luLnNpbl9wb3J0ID0gaHRvbnMoYXRvaShhcmd2WzJdKSk7DQogICAgc2luLnNpbl9hZ';
  $g_DBShe[] = 'aHR0cDovL2otZGV2LnJ1L2luZGV4LnBocD9jcG49ZnJhbWVzZWxs';
  $g_DBShe[] = 'WTJTkCol0X4AuwJSfFhtfP5dOgn561il+wkzkqCG9dfT9zqc274veIeSd41CxUIvHFn+tW77oE3ohqSv01BXzT0';
  $g_DBShe[] = 'HByb3RvKSB8fCBkaWUoIkVycm9yOiAkIVxuIik7DQpjb25uZWN0KFNPQ0tFVCwgJHBhZGRy';
  $g_DBShe[] = 'Web Shell by boff';
  $g_DBShe[] = 'Web Shell by oRb';
  $g_DBShe[] = 'devilzShell';
  $g_DBShe[] = 'Shell by Mawar_Hitam';
  $g_DBShe[] = 'N3tshell';
  $g_DBShe[] = 'Storm7Shell';
  $g_DBShe[] = 'Locus7Shell';
  $g_DBShe[] = 'private Shell by m4rco';
  $g_DBShe[] = 'w4ck1ng shell';
  $g_DBShe[] = 'FaTaLisTiCz_Fx Fx29Sh';
  $g_DBShe[] = 'r57shell.php';
  $g_DBShe[] = 'default_action = \'FilesMan\'';
  $g_DBShe[] = 'Worker_GetReplyCode($opData[\'recvBuffer\'])'; // spammer
  $g_DBShe[] = '$filepath=@realpath($_POST[\'filepath\']);';
  $g_DBShe[] = 'antishell';
  $g_DBShe[] = 'rootshell';
  $g_DBShe[] = 'myshellexec';
  $g_DBShe[] = '$redirectURL=\'http://\'.$rSite.$_SERVER[\'REQUEST_URI\'];if(isset($_SERVER[\'HTTP_REFERER\'])';
  $g_DBShe[] = '40UeCKdB8EOqmXCKeG3qU0YiBjsGWrUHmwLGQgrNouyXEJ9N4tjVvrSQAFDqDnVHG9vDZyBFvw4cTGJoq/PFCUszIStCTYz2ZbLkTKwveMVsNOAfKLI2nAokzk9I3Zjl7pAeBjn';
  $g_DBShe[] = 'IWluHjKpx7/XGqKcH1GHE209LxyiNKz5TKCozJXiquNtOAx3Dx4GKzNVnfUSR/sH8CTAl5q7wodaojO3v+vCDeGE';
  $g_DBShe[] = 'dHUu0dJWVsgDe2rfe4gWBtiLVc5jkpo1LT8LqmeXeWzSXV9F4IBU8i3BcoeArPoPmngR/CYb752fcS9pGAjjFFH0jdIKvj4hMZNnyVU';
  $g_DBShe[] = 'rename("wso.php",';
  $g_DBShe[] = '$MessageSubject = base64_decode($_POST["msgsubject"]);';
  $g_DBShe[] = '0iZGlzcGxheTpub25lIj48YSBocmVmPSJodHRwOi8vd3d3Lmpvb21sYXh0Yy5jb20iPkpvb21sYVhUQyBOZXdz';
  $g_DBShe[] = 'jVNtT9tADP4+af8hQxNtBW0hgQQEbKtKYPsyoQ72pYmqa2Kao';
  $g_DBShe[] = 'copy($_FILES[x][tmp_name],$_FILES[x][name]))';
  $g_DBShe[] = 'Shell Ok';
  $g_DBShe[] = 'Iik7DQpjb25uZWN0KFNPQ0tFVCwgJHBhZGRyKSB8fCBkaWUoIkVycm9yOiAkIVxuIik7DQpvcGVuKFNURElOLCAiPiZTT';
  $g_DBShe[] = 'SELECT 1 FROM mysql.user WHERE concat(`user`, \'@\', `host`)';
  $g_DBShe[] = '!@$_COOKIE[$sessdt_k]';
  $g_DBShe[] = '4YTZiNzMyM2UwMjA1ZGQxNTc0ZGFkMWZiZT0iXHg2ZiI7JG05Nzk0YTY0OWEzYWQzZDg5OTBlOWJiYj';
  $g_DBShe[] = '$a=(substr(urlencode(print_r(array(),1)),5,1).c)';
  $g_DBShe[] = 'xh -s "/usr/local/apache/sbin/httpd -DSSL" ./httpd -m $1';
  $g_DBShe[] = 'pwd > Generasi.dir';
  $g_DBShe[] = 'BRUTEFORCING';
  $g_DBShe[] = 'Cautam fisierele de configurare';
  $g_DBShe[] = 'muiWr4TmLaPwQoJESgLoAnQSv93axqhjRmOADMoF3ZL';
  $g_DBShe[] = '$ka=\'<?//BRE\';$kaka=$ka.\'ACK//?>';
  $g_DBShe[] = '$subj=urldecode($_GET[\'su\']);$body=urldecode($_GET[\'bo\']);$sds=urldecode($_GET[\'sd\'])';
  $g_DBShe[] = '$____=@gzinflate($____)){if(isset($_POS';
  $g_DBShe[] = 'passthru(getenv("HTTP_ACCEPT_LANGUAGE';
  $g_DBShe[] = 'Asmodeus';
  $g_DBShe[] = 'for(;$paddr=accept(CLIENT, SERVER);close CLIENT) {';
  $g_DBShe[] = '$izinler2=substr(base_convert(@fileperms($fname),10,8),-4);';
  $g_DBShe[] = '$backdoor->ccopy($cfichier,$cdestination);';
  $g_DBShe[] = '{${passthru($cmd)}}<br>';
  $g_DBShe[] = '$a[hits]\'); \r\n#endquery\r\n';
  $g_DBShe[] = 'ncftpput -u $ftp_user_name';
  $g_DBShe[] = 'exec("rm -r -f';
  $g_DBShe[] = 'execl("/bin/sh","sh","-i",(char*)0);';
  $g_DBShe[] = '<HTML><HEAD><TITLE>cgi-shell.py';
  $g_DBShe[] = 'system("unset HISTFILE; unset SAVEHIST';
  $g_DBShe[] = 'Ne udalos zagruzit';
  $g_DBShe[] = '$login=@posix_getuid();';
  $g_DBShe[] = '(ereg(\'^[[:blank:]]*cd[[:blank:]]*$\', $_REQUEST[\'command\']))';
  $g_DBShe[] = '!$_REQUEST["c99sh_surl"])';
  $g_DBShe[] = 'PnVlkWM63!@#@&dKx~nMDWM~D/Esn~x6D@#@&P~~,?nY,WP{Poj';
  $g_DBShe[] = 'shell_exec($_POST[\'cmd\'] . " 2>&1");';
  $g_DBShe[] = 'if(!$whoami)$whoami=exec("whoami");';
  $g_DBShe[] = 'PySystemState.initialize(System.getProperties(), null, argv);';
  $g_DBShe[] = '<%=env.queryHashtable("user.name")%>';
  $g_DBShe[] = 'if (empty($_POST[\'wser\'])) {$wser = "whois.ripe.net";} else $wser = $_POST[\'wser\'];';
  $g_DBShe[] = 'if (move_uploaded_file($_FILES[\'fila\'][\'tmp_name\'], $curdir."/".$_FILES[\'fila\'][\'name\'])) {';
  $g_DBShe[] = '/etc/passwd';
  $g_DBShe[] = '/var/cpanel';
  $g_DBShe[] = '/etc/httpd';
  $g_DBShe[] = 'shell_exec(\'uname -a\');';
  $g_DBShe[] = '/etc/named.conf';
  $g_DBShe[] = 'if (!defined$param{cmd}){$param{cmd}="ls -la"};';
  $g_DBShe[] = '$message = ereg_replace("%5C%22", "%22", $message);';
  $g_DBShe[] = 'print "Spamed\'><br>';
  $g_DBShe[] = 'if(get_magic_quotes_gpc())$shellOut=stripslashes($shellOut);';
  $g_DBShe[] = '<a href=\'$PHP_SELF?action=viewSchema&dbname=$dbname&tablename=$tablename\'>Schema</a>';
  $g_DBShe[] = 'passthru( $bindir."mysqldump --user=$USERNAME --password=$PASSWORD';
  $g_DBShe[] = 'mysql_query("CREATE TABLE `xploit` (`xploit` LONGBLOB NOT NULL)");';
  $g_DBShe[] = 'setcookie( "mysql_web_admin_username" );';
  $g_DBShe[] = '$ra44  = rand(1,99999);$sj98 = "sh-$ra44";$ml = "$sd98";$a5 = $_SERVER[\'HTTP_REFERER\'];';
  $g_DBShe[] = '$_FILES[\'probe\'][\'size\'], $_FILES[\'probe\'][\'type\']);';
  $g_DBShe[] = 'system("$cmd 1> /tmp/cmdtemp 2>&1; cat /tmp/cmdtemp; rm /tmp/cmdtemp");';
  $g_DBShe[] = 'elseif(function_exists("shell_exec"))';
  $g_DBShe[] = '} elsif ($servarg =~ /^\:(.+?)\!(.+?)\@(.+?) PRIVMSG (.+?) \:(.+)/) {';
  $g_DBShe[] = 'send(SOCK5, $msg, 0, sockaddr_in($porta, $iaddr)) and $pacotes{o}++;;';
  $g_DBShe[] = '$fe("$cmd  2>&1");';
  $g_DBShe[] = 'while ($row = mysql_fetch_array($result,MYSQL_ASSOC)) print_r($row);';
  $g_DBShe[] = 'elseif(@is_writable($FN) && @is_file($FN)) $tmpOutMF';
  $g_DBShe[] = 'connect(SOCKET, sockaddr_in($ARGV[1], inet_aton($ARGV[0]))) or die print';
  $g_DBShe[] = 'if(move_uploaded_file($_FILES["fic"]["tmp_name"],good_link("./".$_FILES["fic"]["name"])))';
  $g_DBShe[] = 'UNION SELECT \'0\' , \'<? system(\$_GET[cpc]);exit; ?>\' ,0 ,0 ,0 ,0 INTO OUTFILE \'$outfile';
  $g_DBShe[] = 'if (!@is_link($file) && ($r = realpath($file)) != FALSE) $file = $r;';
  $g_DBShe[] = 'echo "FILE UPLOADED TO $dez";';
  $g_DBShe[] = '$function($_POST[\'cmd\'])';
  $g_DBShe[] = '<%#@~^HwAAAA==@#@&DnkwKx/RUN@#@&nx9Pd;(@#@&ugcAAA==^#~@%>';
  $g_DBShe[] = '$filename = $backupstring."$filename";';
  $g_DBShe[] = 'if(\'\'==($df=@ini_get(\'disable_functions\'))){echo';
  $g_DBShe[] = '<% For Each Vars In Request.ServerVariables %>';
  $g_DBShe[] = 'if ($funcarg =~ /^portscan (.*)/)';
  $g_DBShe[] = '$uploadfile = $rpath."/" . $_FILES[\'userfile\'][\'name\'];';
  $g_DBShe[] = '$cmd = ($_REQUEST[\'cmd\']);';
  $g_DBShe[] = 'if($cmd != "") print Shell_Exec($cmd);';
  $g_DBShe[] = 'if (is_file("/tmp/$ekinci")){';
  $g_DBShe[] = '__all__ = ["SMTPServer","DebuggingServer","PureProxy","MailmanProxy"]';
  $g_DBShe[] = 'global $mysqlHandle, $dbname, $tablename, $old_name, $name,';
  $g_DBShe[] = '2>&1 1>&2" : " 1>&1 2>&1");';
  $g_DBShe[] = 'map { read_shell($_) } ($sel_shell->can_read(0.01));';
  $g_DBShe[] = 'fwrite ($fp, "$yazi");';
  $g_DBShe[] = 'Send this file: <INPUT NAME="userfile" TYPE="file">';
  $g_DBShe[] = '$db_d = @mysql_select_db($database,$con1);';
  $g_DBShe[] = 'if (is_callable("exec") and !in_array("exec",$disablefunc))';
  $g_DBShe[] = 'if (($perms & 0xC000) == 0xC000) {';
  $g_DBShe[] = 'for ($value) { s/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g; s/"/&quot;/g; }';
  $g_DBShe[] = 'dir /OG /X';
  $g_DBShe[] = 'ls -la';
  $g_DBShe[] = 'copy($_FILES[\'upkk\'][\'tmp_name\'],"kk/".basename($_FILES[\'upkk\'][\'name\']));';
  $g_DBShe[] = 'ZnVuY3Rpb24geGNjKCRwLCR4PTMxNTM2MDAwKXsgJGYgPSBAZmlsZW10aW1lKCRwKTsgJGNyb24gPSB0aW1lKCkgLSAkZjsgJGQgPSBAZmlsZV9nZ';
  $g_DBShe[] = 'function google_bot() {$sUserAgent = strtolower($_SERVER[\'HTTP_USER_AGENT\']);if(!(strp';
  $g_DBShe[] = 'eva1fYlbakBcVSir';
  $g_DBShe[] = 'create_function("&$"."function","$"."function = chr(ord($"."function)-3);")';
  $g_DBShe[] = 'long int:t(0,3)=r(0,3);-2147483648;2147483647;';
  $g_DBShe[] = '?url=\'.$_SERVER[\'HTTP_HOST\']).unlink(ROOT_DIR.';
  $g_DBShe[] = 'cat ${blklog[2]} | grep "root:x:0:0"';
  $g_DBShe[] = "@path1=('admin/','administrator/','moderator/','webadmin/','adminarea/','bb-admin/','adminLogin/'";
  $g_DBShe[] = '"admin1.php", "admin1.html", "admin2.php", "admin2.html", "yonetim.php", "yonetim.html"';
  $g_DBShe[] = 'find / -type f -perm -04000 -ls';
  $g_DBShe[] = 'find / -type f -perm -02000 -ls';
  $g_DBShe[] = 'find / -type f -name .htpasswd';
  $g_DBShe[] = 'POST {$path}{$connector}?Command=FileUpload&Type=File&CurrentFolder=';
  $g_DBShe[] = '@assert($_REQUEST[\'PHPSESSID\']';
  $g_DBShe[] = 'round(0+';
  $g_DBShe[] = 'eval(base64_decode(\'cGhwaW5mbygpOw==\'))';
  $g_DBShe[] = '$prod="sy"."s"."tem";$id=$prod($_REQUEST[\'product\']);${\'id\'};';
  $g_DBShe[] = 'php ".$wso_path';
  $g_DBShe[] = '$Fchmod,$Fdata,$Options,$Action,$hddall,$hddfree,$hddproc,$uname,$idd):shared';
  $g_DBShe[] = 'ODE1NDVjZGQyZGExNGY5ZjQ4OWFlNWEwMjFkOWEzNjE';
  $g_DBShe[] = 'server.</p>\r\n</body></html>";exit;}if(preg_match(';
  $g_DBShe[] = 'e5WrPYNM5uDUC2wrsZHyRLSDg1yWSmMzPczWmFFAFqGR0ETcrfa5MSQeCcHBEc5ckpZR6CrWv1';
  $g_DBShe[] = 'D10++3qBnHfyh1iI5tZv6vWiO1hVQvDZ5crKV0Ltuyo3qw3cAgMuzB6LXARBS7Ie9BTxm';
  $g_DBShe[] = 'P2lCP1ouWg1Wc0EoJF9DS1RqJ3NIQU8nZD5TUz4nc1l4Jyk+XQ1WLk1lOU16KCIvT0g9TUg';
  $g_DBShe[] = 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA-m62AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQU';
  $g_DBShe[] = 'Lz8_Ly8vDx8e_v7-7u7u3s7uzs7Ozq6unq7erq6uvq5-jo6ujn5';
  $g_DBShe[] = 'DJ7VIU7RICXr6sEEV2cBtHDSOe9nVdpEGhEmvRVRNURfw1wQ';
  $g_DBShe[] = '$file = $_FILES["filename"]["name"]; echo "<a href=\"$file\">$file</a>";} else {echo("empty");}';
  $g_DBShe[] = 'Ly83MTg3OWQyMTJkYzhjYmY0ZDRmZDA0NGEzZDE3Zjk3ZmI2N';
  $g_DBShe[] = 'FS_chk_func_libc=( $(readelf -s $FS_libc | grep _chk@@ | awk';
  $g_DBShe[] = 'find / -name .ssh > $dir/sshkeys/sshkeys';
  $g_DBShe[] = 're.findall(dirt+\'(.*)\',prognm)[0]';
  $g_DBShe[] = 'QOiKWAgV613LvstKY+UB98JZTRGIhYBdHuJCAwm+Xth16AwQ8X4tPMcMVZQte';
  $g_DBShe[] = 'include($_SERVER[\'HTTP_USER_AGENT\'])';
  $g_DBShe[] = 'outstr += string.Format("<a href=\'?fdir={0}\'>{1}/</a>&nbsp;"';
  $g_DBShe[] = '<%=Request.Servervariables("SCRIPT_NAME")%>?txtpath=<%=Request.QueryString("txtpath';
  $g_DBShe[] = 'Response.Write(Server.HtmlEncode(this.ExecuteCommand(txtCommand.Text)))';
  $g_DBShe[] = 'new FileStream(Path.Combine(fileInfo.DirectoryName, Path.GetFileName(httpPostedFile.FileName)), FileMode.Create';
  $g_DBShe[] = 'Response.Write("<br>( ) <a href=?type=1&file=" & server.URLencode(item.path) & "\>" & item';
  $g_DBShe[] = 'sqlCommand.Parameters.Add(((TableCell)dataGridItem.Controls[0]).Text, SqlDbType.Decimal).Value = decimal';
  $g_DBShe[] = '<%= "\\" & oScriptNet.ComputerName & "\" & oScriptNet.UserName %>';
  $g_DBShe[] = '3HjqxclkZfpWb1SwzwTmp1KYDAew+TFt4H3j59kzW6edMRnLP3/tYSBPmf';
  $g_DBShe[] = '5oHnRn6idozNxkU6hhdauLyby6LIqxWVRQdJnW1qHHeMRl59M2Sqw3DkBUzV8KKm1prY9WX';
  $g_DBShe[] = 'bMFiubRwIzqiHhkPkIapTR3dVD5Aokq8mRFdMmkPUXjWRScJ/WfRfLpPPbGy8gtiUpluog0d';
  $g_DBShe[] = 'taoOI8uyLbzISLIN9FsXdK7h+/dd2YnIRUotBlN';
  $g_DBShe[] = 'system("whoami")';
  $g_DBShe[] = 'curl_setopt($ch, CURLOPT_URL, "http://$host:2082")';
  $g_DBShe[] = 'HJ3HjutckoRfpXf9A1zQO2AwDRrRey9uGvTeez79qAao1a0rgudkZkR8Ra';
  $g_DBShe[] = '$ini[\'users\'] = array(\'root\' =>';
  $g_DBShe[] = 'milw0rm';
  $g_DBShe[] = 'AAAAAAAAMAAwABAAAAeAUAADQAAADsCQAAAAAAADQAIAADACgAFwAUAAEA';
  $g_DBShe[] = '\x31\xdb\xf7\xe3\x53\x43\x53\x6a\x02\x89\xe1\xb0\x66\xcd';
  $g_DBShe[] = 'proc_open(\'IHSteam';
  $g_DBShe[] = '$baslik=$_POST[\'baslik\']';
  $g_DBShe[] = 'fread($fp, filesize($fichero))';
  $g_DBShe[] = '97QEXRAs99c98Hdjoh9zZiTR12GazoJUIiLU';
  $g_DBShe[] = '7Vh3WFPZtj8pkEASEiQISDsoCigdRkCDJAIC';
  $g_DBShe[] = 'XVFNawIxEL0L/odhhZJocF2v2oKIBSmtontrZ';
  $g_DBShe[] = '463839610c000b00800100ffffffffffff21f90401000001002c000';
  $g_DBShe[] = '\u003c\u0069\u006d\u0067\u0020\u0073\u0072\u0063\u003d\u0022\u0068\u0074\u0074\u0070\u003a\u002f\u002f';
  $g_DBShe[] = 'FJ3FkuPKFkU/53WEBmIaipktnLwQW8z49dc1rbbLqsw8e69l6vJM+3/124xVn+7l';
  $g_DBShe[] = '\'httpd.conf\',\'vhosts.conf\',\'cfg.php\',\'config.php\'';
  $g_DBShe[] = 'I/gcZ/vX0A10DDRDg7Ezk/d+3+8qvqqS1K0+AXY';
  $g_DBShe[] = '{$_POST[\'root\']}';
  $g_DBShe[] = '}elseif($_GET[\'page\']==\'ddos\'';
  $g_DBShe[] = 'Q3JlZGl0IDogVW5kZXJncm91bmQgRGV2aWwgJm5ic3A7ICB8DQo8YSBocmVmP';
  $g_DBShe[] = 'The Dark Raver';
  $g_DBShe[] = '$value =~ s/%(..)/pack(\'c\',hex($1))/eg;';
  $g_DBShe[] = 'www.t0s.org';
  $g_DBShe[] = 'unless(open(PFD,$g_upload_db))';
  $g_DBShe[] = 'az88pix00q98';
  $g_DBShe[] = 'sh go $1.$x';
  $g_DBShe[] = 'system("php -f xpl $host")';
  $g_DBShe[] = 'exploitcookie';
  $g_DBShe[] = '80 -b $1 -i eth0 -s 8';
  $g_DBShe[] = 'HTTP flood complete after';
  $g_DBShe[] = 'NIGGERS.NIGGERS';
  $g_DBShe[] = 'if(isset($_GET[\'host\'])&&isset($_GET[\'time\'])){';
  $g_DBShe[] = 'subprocess.Popen(cmd, shell = True, stdout=subprocess.PIPE, stderr=subprocess.STDOU';
  $g_DBShe[] = 'def daemon(stdin=\'/dev/null\', stdout=\'/dev/null\', stderr=\'/dev/null\')';
  $g_DBShe[] = 'print("[!] Host: " + hostname + " might be down!\n[!] Response Code';
  $g_DBShe[] = 'connection.send("shell "+str(os.getcwd())+';
  $g_DBShe[] = 'os.system(\'echo alias ls=".ls.bash" >> ~/.bashrc\')';
  $g_DBShe[] = 'rule_req = raw_input("SourceFire';
  $g_DBShe[] = 'argparse.ArgumentParser(description=help, prog="sctunnel"';
  $g_DBShe[] = 'subprocess.Popen(\'%sgdb -p %d -batch %s\' % (gdb_prefix, p';
  $g_DBShe[] = '/proc/sys/kernel/yama/ptrace_scope';
  $g_DBShe[] = '$framework.plugins.load("#{rpctype.downcase}rpc", opts).run';
  $g_DBShe[] = 'if self.hash_type == \'pwdump';
  $g_DBShe[] = 'itsoknoproblembro';
  $g_DBShe[] = 'add_filter(\'the_content\', \'_bloginfo\', 10001)';
  $g_DBShe[] = '<stdlib.h';
  $g_DBShe[] = 'echo y ; sleep 1 ; } | { while read ; do echo z$REPLY; done';
  $g_DBShe[] = 'VOBRA GANGO';
  $g_DBShe[] = 'int32((($z >> 5 & 0x07ffffff) ^ $y << 2) + (($y >> 3 & 0x1fffffff) ^ $z << 4';
  $g_DBShe[] = '@copy($_FILES[fileMass][tmp_name],$_POST[path].$_FILES[fileMass][name';
  $g_DBShe[] = 'find_dirs($grandparent_dir, $level, 1, $dirs);';
  $g_DBShe[] = 'eval(file_get_contents(';
  $g_DBShe[] = '@setcookie("hit", 1, time()+';
  $g_DBShe[] = 'e/*./';
  $g_DBShe[] = 'edoced_46esab';
  $g_DBShe[] = 'JHZpc2l0Y291bnQgPSAkSFRUUF9DT09LSUVfV';
  $g_DBShe[] = 'etalfnizg';
  $g_DBShe[] = '0d0a0d0a676c6f62616c20246d795f736d7';
  $g_DBShe[] = 'is_writable("/var/tmp")';
  $g_DBShe[] = 'f0VMRgEBAQA';
  $g_DBShe[] = 'fopen(\'/etc/passwd\'';
  $g_DBShe[] = 'udp://';
  $g_DBShe[] = '$tsu2[rand(0,count($tsu2) - 1)].$tsu1[rand(0,count($tsu1) - 1)].$tsu2[rand(0';
  $g_DBShe[] = '/usr/local/apache/bin/httpd -DSSL';
  $g_DBShe[] = 'set protect-telnet 0';
  $g_DBShe[] = 'ayu pr1 pr2 pr3 pr4 pr5 pr6';
  $g_DBShe[] = 'bind filt - "\001ACTION *\001"';
  $g_DBShe[] = 'regsub -all -- , [string tolower $owner] "" owners';
  $g_DBShe[] = 'kill -CHLD \$botpid >/dev/null 2>&1';
  $g_DBShe[] = 'bind dcc -';
  $g_DBShe[] = 'r4aTc.dPntE/fztSF1bH3RH0';
  $g_DBShe[] = 'privmsg $chan';
  $g_DBShe[] = 'bind join - * gop_join';
  $g_DBShe[] = 'set google(data) [http::data $google(page)]';
  $g_DBShe[] = 'proc http::Connect {token}';
  $g_DBShe[] = 'privmsg $nick';
  $g_DBShe[] = 'putbot $bot';
  $g_DBShe[] = 'unbind RAW -';
  $g_DBShe[] = '--DCCDIR [lindex $User($i) 2]';
  $g_DBShe[] = '/home/mydir/eggdrop/filesys';
  $g_DBShe[] = 'time() - 105200200';
  $g_DBShe[] = '$GLOBALS[\'____';
  $g_DBShe[] = 'is_callable(\'exec\') and !in_array(\'exec\', $disablefuncs';
  $g_DBShe[] = 'Cybester90';
  $g_DBShe[] = 'k0d.cc';
  $g_DBShe[] = 'file_get_contents(trim($f[$_GET[\'id\']]));';
  $g_DBShe[] = 'unlink($writable_dirs';
  $g_DBShe[] = 'base64_decode($code_script)';
  $g_DBShe[] = 'luciffer@luciffer.org';
  $g_DBShe[] = '$this->F->GetController($_SERVER[\'REQUEST_URI\'])';
  $g_DBShe[] = '$time_started.$secure_session_user.session_id()';
  $g_DBShe[] = '$param x $n.substr ($param, length($param) - length($code)%length($param))';
  $g_DBShe[] = 'ini_set(\'magic_quotes_gpc';
  $g_DBShe[] = 'ini_set("magic_quotes_gpc';
  $g_DBShe[] = 'fwrite($f,get_download($_GET[\'url\'])';
  $g_DBShe[] = 'http://\'.$_SERVER[\'HTTP_HOST\'].urldecode($_SERVER[\'REQUEST_URI\'])';
  $g_DBShe[] = 'wp_posts WHERE post_type = \'post\' AND post_status = \'publish\' ORDER BY `ID` DESC';
  $g_DBShe[] = '$url = $urls[rand(0, count($urls)-1)]';
  $g_DBShe[] = 'preg_match(\'/(?<=RewriteRule).*(?=\[L\,R\=302\]';
  $g_DBShe[] = 'preg_match(\'!MIDP|WAP|Windows.CE|PPC|Series60';
  $g_DBShe[] = 'R0lGODlhEwAQALMAAAAAAP///5ycAM7OY///nP//zv/OnPf39////wAAAAAA';
  $g_DBShe[] = 'str_rot13($basea[($dimension*$dimension-1) - ($i*$dimension+$j)])';
  $g_DBShe[] = 'if(empty($_GET[\'zip\']) and empty($_GET[\'download\']) & empty($_GET[\'img\'])){';
  $g_DBShe[] = 'Made by Delorean';
  $g_DBShe[] = '$eva1t';
  $g_DBShe[] = 'overflow-y:scroll;\">".$links.$html_mf[\'body\']';
  $g_DBShe[] = 'function urlGetContents($url, $timeout = 5)';
  $g_DBShe[] = 'webr00t';
  $g_DBShe[] = 'echo "<script>alert(';
  $g_DBShe[] = 'd3lete';        
  $g_DBShe[] = 'letaksekarang()';
  $g_DBShe[] = 'YENIÇERI';
  $g_DBShe[] = 'Defacer';
  $g_DBShe[] = '$OOO000000=urldecode(';
  $g_DBShe[] = '-I/usr/local/bandmin';
  $g_DBShe[] = 'fwrite($fpsetv, getenv("HTTP_COOKIE")';
  $g_DBShe[] = 'isset($_POST[\'execgate\'])';
  $g_DBShe[] = 'Webcommander at';
  $g_DBShe[] = '== "bindshell"';
  $g_DBShe[] = '^c^a^l^p^e^r^_^g^e^r^p';
  $g_DBShe[] = 'Spamer';
  $g_DBShe[] = 'Pashkela';
  $g_DBShe[] = 'createFilesForInputOutput';
  $g_DBShe[] = 'M4ll3r';
  $g_DBShe[] = '__VIEWSTATEENCRYPTED';
  $g_DBShe[] = 'OoN_Boy';
  $g_DBShe[] = '[ Phproxy ]';
  $g_DBShe[] = 'ReaL_PuNiShEr';
  $g_DBShe[] = 'darkminz';
  $g_DBShe[] = '[coderz]';
  $g_DBShe[] = 'Zed0x';
  $g_DBShe[] = '6esab';
  $g_DBShe[] = 'abacho|abizdirectory|about|acoon|alexana';
  $g_DBShe[] = 'ppc|midp|windows ce|mtk|j2me|symbian';
  $g_DBShe[] = '@chr(($h[$e[$o]]<<4)+($h[$e[++$o]]));}}eval($d)';
  $g_DBShe[] = '$sh3llColor';
  $g_DBShe[] = 'Punker2Bot';
  $g_DBShe[] = '<?php echo "#!!#";';
  $g_DBShe[] = '$im=substr($im,0,$i).substr($im,$i2+1,$i4-($i2+1)).substr($im,$i4+12,strlen';
  $g_DBShe[] = '($indata,$b64=1){if($b64==1){$cd=base64_decode($indata)';
  $g_DBShe[] = '($_POST["dir"]));';
  $g_DBShe[] = 'Hacked By EnDLeSs';
  $g_DBShe[] = 'andex|oogl';
  $g_DBShe[] = 'ndroi|htc_';
  $g_DBShe[] = '#IrIsT';
  $g_DBShe[] = 'Am!r';
  $g_DBShe[] = '7P1td+NWliaI/hWkZ4VX9';
  $g_DBShe[] = 'NinjaVirus Here';
  $g_DBShe[] = '<!--#exec cmd="$HTTP_ACCEPT" -->';
  $g_DBShe[] = '$im=substr($tx,$p+2,$p2-($p+2));';
  $g_DBShe[] = '//NOnaME';
  $g_DBShe[] = 'android|avantgo|blackberry';
  $g_DBShe[] = '3xp1r3';
  $g_DBShe[] = '$md5=md5("$random");';

  print '$g_DBShe = unserialize(base64_decode("' . base64_encode(serialize(array_reverse($g_DBShe))) . '"));<br>' . "\n";


   $g_FlexDBShe[] = '$_<gpc>[<s><q>p2<q><s>]<s>==<s><q>chmod<q>';
   $g_FlexDBShe[] = 'Captain<s1>Crunch<s1>Team';
   $g_FlexDBShe[] = 'by<s1>Grinay';
   $g_FlexDBShe[] = 'hacked<s1>by<s1>Hmei7';
   $g_FlexDBShe[] = 'system<s1>file<s1>do<s1>not<s1>delete';
   $g_FlexDBShe[] = 'default_action<s>=<s>\'FilesMan'; 
   $g_FlexDBShe[] = '$info .= (($perms<s>&<s>0x0040)<s>?(($perms<s>&<s>0x0800)<s>?<s>\'s\'<s>:<s>\'x\'<s>)<s>:(($perms<s>&<s>0x0800)<s>?<s>\'S\'<s>:<s>\'-\'<s>)';
  // $g_FlexDBShe[] = '<textarea name=\"phpev\" rows=\"5\" cols=\"150\">".@$_POST[\'phpev\']."</textarea><br>';
  // $g_FlexDBShe[] = 'Executed command: <b><font color=#dcdcdc>[$cmd]';
  // $g_FlexDBShe[] = '[Av4bfCYCS,xKWk$+TkUS,xnGdAx[O';
  // $g_FlexDBShe[] = 'crlf.\'unlink($name);\'.$crlf.\'rename("~".$name, $name);\'.$crlf.\'unlink("grp_repair.php"';
  // $g_FlexDBShe[] = '/0tVSG/Suv0Ur/haUYAdn3jMQwbbocGffAeC29BN9tmBiJdV1lk+jYDU92C94jdtDif+xOYjG6CLhx31Uo9x9/eAWgsBK60kK2mLwqzqd';
  // $g_FlexDBShe[] = 'mpty($_POST[\'ur\'])) $mode |= 0400; if (!empty($_POST[\'uw\'])) $mode |= 0200; if (!empty($_POST[\'ux\'])) $mode |= 0100';
  // $g_FlexDBShe[] = 'nt)(disk_total_space(getcwd())/(1024*1024)) . "Mb " . "Free space " . (int)(disk_free_space(getcwd())/(1024*1024)) . "Mb <';
  // $g_FlexDBShe[] = 'RootShell!\');self.location.href=\'http:';
  // $g_FlexDBShe[] = 'print((is_readable($f) && is_writeable($f))?"<tr><td>".w(1).b("R".w(1).font(\'red\',\'RW\',3)).w(1):(((is_readable($f))?"<tr><td>".w(1).b("R").w(4):"").((is_writabl';
  // $g_FlexDBShe[] = '(\'"\',\'&quot;\',$fn)).\'";document.list.submit();\\\'>\'.htmlspecialchars(strlen($fn)>format?substr($fn,0,format-3).\'...\':$fn).\'</a>\'.str_repeat(\' \',format-strlen($fn)';
   $g_FlexDBShe[] = 'WSOsetcookie<s>(<s>md5<s>(<s>@<m>$_SERVER[<s>\'HTTP_HOST\'<s>]<s>)';
   $g_FlexDBShe[] = 'WSOsetcookie<s>(<s>md5<s>(<s>@<m>$_SERVER[<s>"HTTP_HOST"<s>]<s>)';
  // $g_FlexDBShe[] = '</td><td id=fa>[ <a title=\"Home: \'".htmlspecialchars(str_replace("\\", $sep, getcwd()))."\'.\" id=fa href=\"javascript:ViewDir(\'".rawurlencode';
   $g_FlexDBShe[] = 'Content-Type:<s>$_';
  // $g_FlexDBShe[] = '<nobr><b>$cdir$cfile</b> (".$file["size_str"].")</nobr></td></tr><form name=curr_file>';
   $g_FlexDBShe[] = 'wsoEx<s>(<s>\'<s>tar<s>cfzv<s>\'<s>.<s>escapeshellarg<s>(<s>$_POST[<s>\'p2\'<s>]<s>)';
   $g_FlexDBShe[] = 'eval<s>(<m><s>base64_decode<s>(<m><s>@<m>$_';
  // $g_FlexDBShe[] = 'if (ereg(\'^[[:blank:]]*cd[[:blank:]]+([^;]+)$\', $command, $regs))';
   $g_FlexDBShe[] = 'round<s>(<s>0<s>+';
  // $g_FlexDBShe[] = 'Worker_GetReplyCode($opData[\'recvBuffer\'])'; // spammer
   $g_FlexDBShe[] = 'filepath<s>=<s>@<m>realpath<s>(<s>$_POST<s>[<s>\'filepath\'<s>]<s>)';
   $g_FlexDBShe[] = 'filepath<s>=<s>@<m>realpath<s>(<s>$_POST<s>[<s>"filepath"<s>]<s>)';
  // $g_FlexDBShe[] = '$redirectURL=\'http://\'.$rSite.$_SERVER[\'REQUEST_URI\'];if(isset($_SERVER[\'HTTP_REFERER\'])';
   $g_FlexDBShe[] = 'rename<s>(<s><q>wso.php<q><s>,';
   $g_FlexDBShe[] = '$MessageSubject<s>=<s>base64_decode<s>(<s>$_POST<s>[<s><q>msgsubject<q><s>]<s>)';
   $g_FlexDBShe[] = 'SELECT<s1>1<s1>FROM<s1>mysql.user<s1>WHERE<s1>concat(<s>`user`<s>,<s>\'@\'<s>,<s>`host`<s>)';
  // $g_FlexDBShe[] = '!@$_COOKIE[$sessdt_k]';
  // $g_FlexDBShe[] = '$a=(substr(urlencode(print_r(array(),1)),5,1).c)';
  // $g_FlexDBShe[] = 'xh -s "/usr/local/apache/sbin/httpd -DSSL" ./httpd -m $1';
  // $g_FlexDBShe[] = 'pwd > Generasi.dir';
   $g_FlexDBShe[] = 'eval<s>(<m><s>gzinflate<s>(<m><s>str_rot13';
  // $g_FlexDBShe[] = '$subj=urldecode($_GET[\'su\']);$body=urldecode($_GET[\'bo\']);$sds=urldecode($_GET[\'sd\'])';
  // $g_FlexDBShe[] = '$____=@gzinflate($____)){if(isset($_POS';
   $g_FlexDBShe[] = 'passthru<s>(<m><s>getenv<s>(<m><s>"HTTP_ACCEPT_LANGUAGE';
   $g_FlexDBShe[] = 'passthru<s>(<m><s>getenv<s>(<m><s>\'HTTP_ACCEPT_LANGUAGE';
  // $g_FlexDBShe[] = 'for(;$paddr=accept(CLIENT, SERVER);close CLIENT) {';
  // $g_FlexDBShe[] = '$izinler2=substr(base_convert(@fileperms($fname),10,8),-4);';
  // $g_FlexDBShe[] = '$backdoor->ccopy($cfichier,$cdestination);';
   $g_FlexDBShe[] = '{<s>$<s>{<s>passthru<s>(<m><s>$cmd<s>)<s>}<s>}<s><br>';
  // $g_FlexDBShe[] = '$a[hits]\'); \r\n#endquery\r\n';
   $g_FlexDBShe[] = 'runcommand<s>(<s><q>shellhelp<q><s>,<s><q><gpc><q>';
   $g_FlexDBShe[] = 'ncftpput<s>-u<s>$ftp_user_name';
   $g_FlexDBShe[] = 'exec<s>(<m><s><q>rm<s>-r<s>-f';
   $g_FlexDBShe[] = 'exec<s>(<m><s><q>rm<s>-rf';
   $g_FlexDBShe[] = 'exec<s>(<m><s><q>rm<s>-fr';
  // $g_FlexDBShe[] = 'execl("/bin/sh","sh","-i",(char*)0);';
  // $g_FlexDBShe[] = 'system("unset HISTFILE; unset SAVEHIST';
   $g_FlexDBShe[] = '$login<s>=<s>@<m>posix_getuid(<m><s>)<m>';
  // $g_FlexDBShe[] = '(ereg(\'^[[:blank:]]*cd[[:blank:]]*$\', $_REQUEST[\'command\']))';
   $g_FlexDBShe[] = '!@<m>$_REQUEST<s>[<s>"c99sh_surl"<s>]<s>)';
   $g_FlexDBShe[] = 'shell_exec<s>(<m><s>@<m>$_POST<s>[<s><q><a><q><s>]<s>.<s>"<s>2<s>><s>&1<s>"<s>)<m>';
  // $g_FlexDBShe[] = 'if(!$whoami)$whoami=exec("whoami");';
  // $g_FlexDBShe[] = 'PySystemState.initialize(System.getProperties(), null, argv);';
  // $g_FlexDBShe[] = 'if (empty($_POST[\'wser\'])) {$wser = "whois.ripe.net";} else $wser = $_POST[\'wser\'];';
  // $g_FlexDBShe[] = 'if (move_uploaded_file($_FILES[\'fila\'][\'tmp_name\'], $curdir."/".$_FILES[\'fila\'][\'name\'])) {';
   $g_FlexDBShe[] = 'shell_exec<s>(<m><s><q>uname<s1>-a<q><s>)<m>';
  // $g_FlexDBShe[] = 'if (!defined$param{cmd}){$param{cmd}="ls -la"};';
  // $g_FlexDBShe[] = '$message = ereg_replace("%5C%22", "%22", $message);';
  // $g_FlexDBShe[] = 'if(get_magic_quotes_gpc())$shellOut=stripslashes($shellOut);';
  // $g_FlexDBShe[] = '<a href=\'$PHP_SELF?action=viewSchema&dbname=$dbname&tablename=$tablename\'>Schema</a>';
  // $g_FlexDBShe[] = 'passthru( $bindir."mysqldump --user=$USERNAME --password=$PASSWORD';
  // $g_FlexDBShe[] = 'mysql_query("CREATE TABLE `xploit` (`xploit` LONGBLOB NOT NULL)");';
   $g_FlexDBShe[] = 'setcookie(<m><s><q>mysql_web_admin_username<q><s>)<m>';
  // $g_FlexDBShe[] = '$ra44  = rand(1,99999);$sj98 = "sh-$ra44";$ml = "$sd98";$a5 = $_SERVER[\'HTTP_REFERER\'];';
  // $g_FlexDBShe[] = '$_FILES[\'probe\'][\'size\'], $_FILES[\'probe\'][\'type\']);';
   $g_FlexDBShe[] = 'system("$cmd<s1>1><s>/tmp/cmdtemp<s1>2>&1;<s>cat<s1>/tmp/cmdtemp;<s>rm<s1>/tmp/cmdtemp");';
   $g_FlexDBShe[] = 'if<s>(<s>function_exists<s>(<s><q><cmdl><q><s>)<s>)';
  // $g_FlexDBShe[] = '} elsif ($servarg =~ /^\:(.+?)\!(.+?)\@(.+?) PRIVMSG (.+?) \:(.+)/) {';
  // $g_FlexDBShe[] = 'send(SOCK5, $msg, 0, sockaddr_in($porta, $iaddr)) and $pacotes{o}++;;';
   $g_FlexDBShe[] = '$fe("$cmd<s1>2>&1");';
  // $g_FlexDBShe[] = 'while ($row = mysql_fetch_array($result,MYSQL_ASSOC)) print_r($row);';
  // $g_FlexDBShe[] = 'elseif(@is_writable($FN) && @is_file($FN)) $tmpOutMF';
  // $g_FlexDBShe[] = 'connect(SOCKET, sockaddr_in($ARGV[1], inet_aton($ARGV[0]))) or die print';
  // $g_FlexDBShe[] = 'if(move_uploaded_file($_FILES["fic"]["tmp_name"],good_link("./".$_FILES["fic"]["name"])))';
  // $g_FlexDBShe[] = 'if (!@is_link($file) && ($r = realpath($file)) != FALSE) $file = $r;';
   $g_FlexDBShe[] = '$function<s>(<m><s>@<m>$_<gpc><s>[<s><q>cmd<q><s>]<s>)<m>';
  // $g_FlexDBShe[] = '$filename = $backupstring."$filename";';
  // $g_FlexDBShe[] = 'if(\'\'==($df=@ini_get(\'disable_functions\'))){echo';
   $g_FlexDBShe[] = 'document.write<s>(<s>unescape<s>(<s><q>%3C';
  // $g_FlexDBShe[] = 'if ($funcarg =~ /^portscan (.*)/)';
  // $g_FlexDBShe[] = '$uploadfile = $rpath."/" . $_FILES[\'userfile\'][\'name\'];';
   $g_FlexDBShe[] = '$cmd<s>=<s>(<s>@<m>$_<gpc><s>[<s><q><a><q><s>]<s>)';
  // $g_FlexDBShe[] = 'if($cmd != "") print Shell_Exec($cmd);';
  // $g_FlexDBShe[] = 'if (is_file("/tmp/$ekinci")){';
  // $g_FlexDBShe[] = '__all__ = ["SMTPServer","DebuggingServer","PureProxy","MailmanProxy"]';
  // $g_FlexDBShe[] = 'global $mysqlHandle, $dbname, $tablename, $old_name, $name,';
  // $g_FlexDBShe[] = '2>&1 1>&2" : " 1>&1 2>&1");';
  // $g_FlexDBShe[] = 'map { read_shell($_) } ($sel_shell->can_read(0.01));';
  // $g_FlexDBShe[] = 'fwrite ($fp, "$yazi");';
  // $g_FlexDBShe[] = 'Send this file: <INPUT NAME="userfile" TYPE="file">';
  // $g_FlexDBShe[] = '$db_d = @mysql_select_db($database,$con1);';
   $g_FlexDBShe[] = 'if<s>(<s>is_callable<s>(<m><s><q><cmdl><q><s>)<m>';
  // $g_FlexDBShe[] = 'if (($perms & 0xC000) == 0xC000) {';
  // $g_FlexDBShe[] = 'for ($value) { s/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g; s/"/&quot;/g; }';
  // $g_FlexDBShe[] = 'dir /OG /X';
   $g_FlexDBShe[] = 'ls<s1>-la';
  // $g_FlexDBShe[] = 'copy($_FILES[\'upkk\'][\'tmp_name\'],"kk/".basename($_FILES[\'upkk\'][\'name\']));';
  // $g_FlexDBShe[] = 'function google_bot() {$sUserAgent = strtolower($_SERVER[\'HTTP_USER_AGENT\']);if(!(strp';
   $g_FlexDBShe[] = 'eva1<a>Sir';
  // $g_FlexDBShe[] = 'create_function("&$"."function","$"."function = chr(ord($"."function)-3);")';
  // $g_FlexDBShe[] = 'long int:t(0,3)=r(0,3);-2147483648;2147483647;';
  // $g_FlexDBShe[] = '?url=\'.$_SERVER[\'HTTP_HOST\']).unlink(ROOT_DIR.';
  // $g_FlexDBShe[] = 'cat ${blklog[2]} | grep "root:x:0:0"';
  // $g_FlexDBShe[] = "@path1=('admin/','administrator/','moderator/','webadmin/','adminarea/','bb-admin/','adminLogin/'";
  // $g_FlexDBShe[] = '"admin1.php", "admin1.html", "admin2.php", "admin2.html", "yonetim.php", "yonetim.html"';
  // $g_FlexDBShe[] = 'find / -type f -perm -04000 -ls';
  // $g_FlexDBShe[] = 'find / -type f -perm -02000 -ls';
  // $g_FlexDBShe[] = 'find / -type f -name .htpasswd';
  // $g_FlexDBShe[] = 'POST {$path}{$connector}?Command=FileUpload&Type=File&CurrentFolder=';
   $g_FlexDBShe[] = '@<m>assert<s>(<m><s>$_<gpc><s>[<s><q><a><q><s>]<s>';
  // $g_FlexDBShe[] = '$prod="sy"."s"."tem";$id=$prod($_REQUEST[\'product\']);${\'id\'};';
   $g_FlexDBShe[] = 'php<s1>"<s>.<s>$wso_path';
  // $g_FlexDBShe[] = '$Fchmod,$Fdata,$Options,$Action,$hddall,$hddfree,$hddproc,$uname,$idd):shared';
  // $g_FlexDBShe[] = 'server.</p>\r\n</body></html>";exit;}if(preg_match(';
   $g_FlexDBShe[] = 'eval<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'assert<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'base64_decode<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'include<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'require<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'include<s>(<m><s><q>images/';
   $g_FlexDBShe[] = 'require<s>(<m><s><q>images/';
   $g_FlexDBShe[] = 'include_once<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'require_once<s>(<m><s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'include_once<s>(<m><s><q>images/';
   $g_FlexDBShe[] = 'require_once<s>(<m><s><q>images/';
   $g_FlexDBShe[] = '<cmdl><s>(<m><s>@<m>$_<gpc><s>[';
  // $g_FlexDBShe[] = '$file = $_FILES["filename"]["name"]; echo "<a href=\"$file\">$file</a>";} else {echo("empty");}';
  // $g_FlexDBShe[] = 'FS_chk_func_libc=( $(readelf -s $FS_libc | grep _chk@@ | awk';
   $g_FlexDBShe[] = 'find<s1>/<s1>-name<s1>.ssh<s1>><s1>$dir/sshkeys/sshkeys';
  // $g_FlexDBShe[] = 're.findall(dirt+\'(.*)\',prognm)[0]';
  // $g_FlexDBShe[] = 'outstr += string.Format("<a href=\'?fdir={0}\'>{1}/</a>&nbsp;"';
  // $g_FlexDBShe[] = 'Response.Write(Server.HtmlEncode(this.ExecuteCommand(txtCommand.Text)))';
  // $g_FlexDBShe[] = 'new FileStream(Path.Combine(fileInfo.DirectoryName, Path.GetFileName(httpPostedFile.FileName)), FileMode.Create';
  // $g_FlexDBShe[] = 'Response.Write("<br>( ) <a href=?type=1&file=" & server.URLencode(item.path) & "\>" & item';
  // $g_FlexDBShe[] = 'sqlCommand.Parameters.Add(((TableCell)dataGridItem.Controls[0]).Text, SqlDbType.Decimal).Value = decimal';
   $g_FlexDBShe[] = 'system<s>(<m><s><q>whoami<q><s>)<m>';
   $g_FlexDBShe[] = 'curl_setopt<s>(<s>$ch<s>,<s>CURLOPT_URL<s>,<s><q>http://$host:<d><q><s>)';
   $g_FlexDBShe[] = '$ini<s>[<s><q>users<q><s>]<s>=<s>array<s>(<s><q>root<q><s>=>';
   $g_FlexDBShe[] = 'proc_open<s>(<s><q>IHSteam';
  // $g_FlexDBShe[] = '$baslik=$_POST[\'baslik\']';
  // $g_FlexDBShe[] = 'fread($fp, filesize($fichero))';
   $g_FlexDBShe[] = '<q>httpd.conf<q><s>,<s><q>vhosts.conf<q><s>,<s><q>cfg.php<q><s>,<s><q>config.php<q>';
   $g_FlexDBShe[] = '<s>{<s>$_<gpc><s>[<s><q>root<q><s>]<s>}';
  // $g_FlexDBShe[] = '}elseif($_GET[\'page\']==\'ddos\'';
  // $g_FlexDBShe[] = '$value =~ s/%(..)/pack(\'c\',hex($1))/eg;';
  // $g_FlexDBShe[] = 'unless(open(PFD,$g_upload_db))';
  // $g_FlexDBShe[] = 'sh go $1.$x';
  // $g_FlexDBShe[] = 'system("php -f xpl $host")';
  // $g_FlexDBShe[] = '80 -b $1 -i eth0 -s 8';
  // $g_FlexDBShe[] = 'if(isset($_GET[\'host\'])&&isset($_GET[\'time\'])){';
  // $g_FlexDBShe[] = 'subprocess.Popen(cmd, shell = True, stdout=subprocess.PIPE, stderr=subprocess.STDOU';
  // $g_FlexDBShe[] = 'def daemon(stdin=\'/dev/null\', stdout=\'/dev/null\', stderr=\'/dev/null\')';
  // $g_FlexDBShe[] = 'print("[!] Host: " + hostname + " might be down!\n[!] Response Code';
  // $g_FlexDBShe[] = 'connection.send("shell "+str(os.getcwd())+';
  // $g_FlexDBShe[] = 'os.system(\'echo alias ls=".ls.bash" >> ~/.bashrc\')';
  // $g_FlexDBShe[] = 'rule_req = raw_input("SourceFire';
  // $g_FlexDBShe[] = 'argparse.ArgumentParser(description=help, prog="sctunnel"';
  // $g_FlexDBShe[] = 'subprocess.Popen(\'%sgdb -p %d -batch %s\' % (gdb_prefix, p';
  // $g_FlexDBShe[] = '$framework.plugins.load("#{rpctype.downcase}rpc", opts).run';
  // $g_FlexDBShe[] = 'if self.hash_type == \'pwdump';
   $g_FlexDBShe[] = 'eval<s>(<m><s>get_option<s>(<m>';
   $g_FlexDBShe[] = 'add_filter<s>(<m><s><q>the_content<q><s>,<s><q>_bloginfo<q><s>,<s><a>)<m>';
  // $g_FlexDBShe[] = 'echo y ; sleep 1 ; } | { while read ; do echo z$REPLY; done';
  // $g_FlexDBShe[] = 'int32((($z >> 5 & 0x07ffffff) ^ $y << 2) + (($y >> 3 & 0x1fffffff) ^ $z << 4';
  // $g_FlexDBShe[] = '@copy($_FILES[fileMass][tmp_name],$_POST[path].$_FILES[fileMass][name';
  // $g_FlexDBShe[] = 'find_dirs($grandparent_dir, $level, 1, $dirs);';
   $g_FlexDBShe[] = 'preg_replace<s>(<m><s><q>/.*/e<q>';
   $g_FlexDBShe[] = 'eval<s>(<m><s>file_get_contents<s>(<m>';
   $g_FlexDBShe[] = '@<m>setcookie<s>(<m><s><q>hit<q>,<s>1<s>,<s>time<s>(<m><s>)<m><s>+';
   $g_FlexDBShe[] = 'is_writable<s>(<m><s><q>/var/tmp<q><s>)<m>';
   $g_FlexDBShe[] = 'eval<s>(<m>@<m><s>stripslashes<s>(<m><s>@<m>$_';
   $g_FlexDBShe[] = 'eval<s>(<m>@<m><s>stripslashes<s>(<m><s>array_pop<s>(<m><s>@<m>$_';
   $g_FlexDBShe[] = 'fopen<s>(<m><s><q>/etc/passwd<q>';
   $g_FlexDBShe[] = 'rm<s1>-rf';
   $g_FlexDBShe[] = 'rm<s1>-fr';
   $g_FlexDBShe[] = 'rm<s1>-r<s1>-f';
   $g_FlexDBShe[] = 'rm<s1>-f<s1>-r';
  // $g_FlexDBShe[] = 'udp://';
  // $g_FlexDBShe[] = '$tsu2[rand(0,count($tsu2) - 1)].$tsu1[rand(0,count($tsu1) - 1)].$tsu2[rand(0';
  // $g_FlexDBShe[] = '/usr/local/apache/bin/httpd -DSSL';
  // $g_FlexDBShe[] = 'set protect-telnet 0';
  // $g_FlexDBShe[] = 'ayu pr1 pr2 pr3 pr4 pr5 pr6';
  // $g_FlexDBShe[] = 'bind filt - "\001ACTION *\001"';
  // $g_FlexDBShe[] = 'regsub -all -- , [string tolower $owner] "" owners';
  // $g_FlexDBShe[] = 'kill -CHLD \$botpid >/dev/null 2>&1';
  // $g_FlexDBShe[] = 'bind dcc -';
  // $g_FlexDBShe[] = 'r4aTc.dPntE/fztSF1bH3RH0';
  // $g_FlexDBShe[] = 'privmsg $chan';
  // $g_FlexDBShe[] = 'bind join - * gop_join';
  // $g_FlexDBShe[] = 'set google(data) [http::data $google(page)]';
  // $g_FlexDBShe[] = 'proc http::Connect {token}';
  // $g_FlexDBShe[] = 'privmsg $nick';
  // $g_FlexDBShe[] = 'putbot $bot';
  // $g_FlexDBShe[] = 'unbind RAW -';
  // $g_FlexDBShe[] = '--DCCDIR [lindex $User($i) 2]';
  // $g_FlexDBShe[] = 'time() - 105200200';
   $g_FlexDBShe[] = '$GLOBALS[<q>____';
   $g_FlexDBShe[] = 'is_callable<s>(<m><s><q><cmdl><q>)<m><s1>and<s1>!in_array<s>(<m><s><q><cmdl><q><s>,<s>$disablefuncs';
   $g_FlexDBShe[] = 'file_get_contents<s>(<m><s>trim<s>(<s>$<a>[$_<gpc>[<q><a><q>]]));';
  // $g_FlexDBShe[] = 'unlink($writable_dirs';
  // $g_FlexDBShe[] = 'base64_decode($code_script)';
  // $g_FlexDBShe[] = '$this->F->GetController($_SERVER[\'REQUEST_URI\'])';
  // $g_FlexDBShe[] = '$time_started.$secure_session_user.session_id()';
  // $g_FlexDBShe[] = '$param x $n.substr ($param, length($param) - length($code)%length($param))';
  // $g_FlexDBShe[] = 'ini_set(\'magic_quotes_gpc';
  // $g_FlexDBShe[] = 'ini_set("magic_quotes_gpc';
  // $g_FlexDBShe[] = 'fwrite($f,get_download($_GET[\'url\'])';
  // $g_FlexDBShe[] = 'http://\'.$_SERVER[\'HTTP_HOST\'].urldecode($_SERVER[\'REQUEST_URI\'])';
   $g_FlexDBShe[] = 'wp_posts<s1>WHERE<s1>post_type<s>=<s><q>post<q><s1>AND<s1>post_status<s>=<s><q>publish<q><s1>ORDER<s1>BY<s1>`ID`<s1>DESC';
  // $g_FlexDBShe[] = '$url = $urls[rand(0, count($urls)-1)]';
  // $g_FlexDBShe[] = 'preg_match(\'/(?<=RewriteRule).*(?=\[L\,R\=302\]';
  // $g_FlexDBShe[] = 'preg_match(\'!MIDP|WAP|Windows.CE|PPC|Series60';
  // $g_FlexDBShe[] = 'str_rot13($basea[($dimension*$dimension-1) - ($i*$dimension+$j)])';
   $g_FlexDBShe[] = 'strrev(<m><s><q>tressa<q><s>)<m>';
   $g_FlexDBShe[] = 'strrev(<m><s><q>edoced_46esab<q><s>)<m>';
  // $g_FlexDBShe[] = 'if(empty($_GET[\'zip\']) and empty($_GET[\'download\']) & empty($_GET[\'img\'])){';
   $g_FlexDBShe[] = 'function<s1>urlGetContents<s>(<m><s>$url<s>,<s>$timeout<s>=<s><d><s>)';
   $g_FlexDBShe[] = '$OOO<a>=<s>urldecode<s>(<m>';
   $g_FlexDBShe[] = 'symlink<s>(<m><s><q>/home/';
   $g_FlexDBShe[] = 'Options<s1>FollowSymLinks<s1>MultiViews<s1>Indexes<s1>ExecCGI';
   $g_FlexDBShe[] = 'fwrite<s>(<m><s>$fpsetv<s>,<s>getenv<s>(<s><q>HTTP_COOKIE<q><s>)<s>';
   $g_FlexDBShe[] = 'isset<s>(<m><s>$_POST<s>[<s><q>execgate<q><s>]<s>)<m>';
   $g_FlexDBShe[] = 'isset(<m>$_@<m><gpc>[<q><a><q>])<m><s>or<s>die(<m><am>)<m>';
  // $g_FlexDBShe[] = '== "bindshell"';
   $g_FlexDBShe[] = 'UNION<s1>SELECT<s1><q>0<q><s>,<s><q><? system(\$_<gpc>[cpc]);exit;<s>?><q><s>,<s>0<s>,0<s>,<s>0<s>,<s>0<s1>INTO<s1>OUTFILE<s1><q>$<q>';
   $g_FlexDBShe[] = '$GLOBALS[<q><a><q>]=Array<s>(<s>base64_decode<s>(<s><q><a><q><s>)<s>,<s>base64_decode<s>(<s><q><a><q><s>)';
   $g_FlexDBShe[] = 'preg_replace<s>(<m><s><q>/.*[<a>]?/e<q><s>,<s>str_replace';
   $g_FlexDBShe[] = '$GLOBALS[<s><q><a><q><s>][<s><d><s>](<s>$_<d><s>,<s>_<d><s>(<s><d><s>)<s>)<s>)';
   $g_FlexDBShe[] = '$beecode<s>=@<m>file_get_contents<s><q>(<m><s>$urlpurs<s><q>)<m><s>;<s>echo<s1><q>$beecode<q>';
   $g_FlexDBShe[] = '$x<d><s>=<s><q><a><q><s>;<s>$x<d><s>=<s><q><a><q><s>;<s>$x<d><s>=<s><q>';
   $g_FlexDBShe[] = '<?php<s1>$_F<s>=<s>__FILE__<s>;<s>$_X<s>=';
   $g_FlexDBShe[] = 'if<s1>(<m><s>mail<s>(<s>$recp<s>,<s>$subj<s>,<s>$stunt<s>,<s>$frm';
   $g_FlexDBShe[] = 'if<s1>(<s>strpos<s>(<s>$url<s>,<s><q>js/mootools.js<q><s>)<s>===<s>false<s1>&&<s1>strpos<s>(<s>$url<s>,<s><q>js/caption.js<q>';
   $g_FlexDBShe[] = '<cmdl>(<m><q>cd<s1>/tmp';
   $g_FlexDBShe[] = 'eval<s>(<m><s>stripslashes<s>(<m><s>array_pop(<m>$_<gpc>';
   $g_FlexDBShe[] = 'if<s>(<m><s>isset<s>(<m><s>$_<gpc><s>[<s><q><ava><q><s>]<s>)<m><s>)<s>{<s>$<ava><s>=<s>$_<gpc><s>[<s><q><ava><q><s>];<s>eval<s>(<m><s>$<ava><s>)<m>';
   $g_FlexDBShe[] = 'preg_replace<s>(<s><q>/^(www|ftp)\./i<q><s>,<s><q><q>,<s>@$_SERVER<s>[<s><q>HTTP_HOST<q><s>]<s>)';
   $g_FlexDBShe[] = 'stream_socket_client<s>(<s><q>tcp://';
   $g_FlexDBShe[] = 'if<s>(!function_exists<s>(<s><q>posix_getpwuid<q><s>)<s>&&<s>!in_array<s>(<s><q>posix_getpwuid<q>';
   $g_FlexDBShe[] = '=<s>preg_split<s>(<s><q>/\,(\ +)?/<q>,<s>@<m>ini_get<s>(<s><q>disable_functions<q>)';
   $g_FlexDBShe[] = '$<amc><s>(<s><d><s>^<s><d><s>)<s>.<s>$<amc><s>(<s><d><s>^<s><d><s>)<s>.<s>$<amc><s>(<s><d><s>^<s><d><s>)';
   $g_FlexDBShe[] = '$b<s>.<s>$p<s>.<s>$h<s>.<s>$k<s>.<s>$v';
   $g_FlexDBShe[] = '(<s><q>INSHELL<q><s>';
   $g_FlexDBShe[] = 'pcntl_exec';
   $g_FlexDBShe[] = '<gpc><s>[<s><q>___<q><s>';
   $g_FlexDBShe[] = 'AddType<s1>application/x-httpd-php';
   $g_FlexDBShe[] = 'AddHandler<s1>php-script';
   $g_FlexDBShe[] = 'gzuncompress<s>(<m><s>substr<s>(<m><s>base64_decode';
   $g_FlexDBShe[] = 'array_pop<s>(<m><s>$workReplace<s>,<s>$_<gpc><s>,<s>$countKeysNew';
   $g_FlexDBShe[] = 'if<s>(<m><s>@<m>preg_match<s>(<m><s>str';
   $g_FlexDBShe[] = '@$_COOKIE[<q>statCounter<q>]';
   $g_FlexDBShe[] = 'fopen<s>(<m><s>"http://"<s>.<s>$check_domain<s>.<s>":80"<s>.<s>$check_doc<s>,<s>"r"';
   $g_FlexDBShe[] = '@<m>gzinflate<s>(<s>@<m>base64_decode<s>(<s>@<m>str_replace';
   $g_FlexDBShe[] = '$___<s>=';
   $g_FlexDBShe[] = '=<s>array_map<s>(<m><s>strrev<s>';
   $g_FlexDBShe[] = 'file_put_contentz<s>(<m><s>$';
   $g_FlexDBShe[] = 'is__writable<s>(<m><s>$path<s>.<s>uniqid<s>(<m><s>mt_rand';
   $g_FlexDBShe[] = '&&<s>function_exists<s>(<m><s><q>getmxrr<q>)<s>)<s>{<s>@getmxrr<s>(<m><s>$';
   $g_FlexDBShe[] = '$postResult<s>=<s>curl_exec<s>(<m><s>$ch';
   $g_FlexDBShe[] = 'function<s1>sql2_safe<s>(<s>';
   $g_FlexDBShe[] = 'strpos<s>(<m><s>$_SERVER[<s><q>HTTP_USER_AGENT<q><s>]';
   $g_FlexDBShe[] = 'strstr<s>(<m><s>$_SERVER[<s><q>HTTP_USER_AGENT<q><s>]';
   $g_FlexDBShe[] = 'strchr<s>(<m><s>$_SERVER[<s><q>HTTP_USER_AGENT<q><s>]';
   $g_FlexDBShe[] = 'exit<s>(<s><q><script><s>setTimeout<s>(<s>\<q>document.location.href';
   $g_FlexDBShe[] = 'document.write<s>(<s><q><script<s1>src=<q>http://<?=$domain?>/';
   $g_FlexDBShe[] = 'eval(stripslashes(\$_REQUEST';
   $g_FlexDBShe[] = '!touch(<q>../../language/';
   $g_FlexDBShe[] = '<q>aHR0cD';
   $g_FlexDBShe[] = 'Dc0RHa<q>';
   $g_FlexDBShe[] = 'header<s>(<q>Location:<s><q><s>.<s>$to<s>.<s>urldecode';
   $g_FlexDBShe[] = 'if<s>(<s>preg_match<s>(<s><q>#yandex';
   $g_FlexDBShe[] = 'if<s>(<s>stripos<s>(<s>$_SERVER[<q>HTTP_USER_AGENT<q>]<s>,<s><q>Android<q>)<s>!==false<s>&&<s>!$_COOKIE[<q>dle_user_id';
   $g_FlexDBShe[] = 'echo<s1>@file_get_contents<s>(<s>$get';
   $g_FlexDBShe[] = 'default_action<s>=<s><q>FilesMan<q>';
   $g_FlexDBShe[] = 'define<s>(<s><q>DEFCALLBACKMAIL';
   $g_FlexDBShe[] = '$headers<s>.=<s>$_POST[<q>eMailAdd<q>]';
   $g_FlexDBShe[] = 'Mysterious<s1>Wire';
   $g_FlexDBShe[] = 'preg_replace<s>(<m><s><q>/.+/esi';
   $g_FlexDBShe[] = 'define<s>(<m><s><q>SBCID_REQUEST_FILE<q><s>,';
   $g_FlexDBShe[] = 'str_ireplace<s>(<m><s><q></head>';
   $g_FlexDBShe[] = '$tld<s>=<s>array<s>(<s><q>com<q>,<q>org<q>,<q>net<q>';
   $g_FlexDBShe[] = 'Brazil<s1>HackTeam';
   $g_FlexDBShe[] = 'eval<s>(<s>base64_decode';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>base64_decode';
   $g_FlexDBShe[] = 'gzuncompress<s>(<s>base64_decode';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>str_rot13<s>(<s>base64_decode';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>base64_decode<s>(<s>str_rot13';
   $g_FlexDBShe[] = 'base64_decode<s>(<s>gzuncompress<s>(<s>base64_decode';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>base64_decode<s>(<s>base64_decode<s>(<s>str_rot13';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>base64_decode<s>(<s>strrev';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>base64_decode<s>(<s>strrev<s>(<s>str_rot13';
   $g_FlexDBShe[] = 'gzinflate<s>(<s>base64_decode<s>(<s>str_rot13<s>(<s>strrev';
   $g_FlexDBShe[] = 'gzuncompress<s>(<s>base64_decode<s>(<s>str_rot13';
   $g_FlexDBShe[] = 'gzuncompress<s>(<s>str_rot13<s>(<s>base64_decode';
   $g_FlexDBShe[] = 'str_rot13<s>(<s>gzinflate<s>(<s>base64_decode';
   $g_FlexDBShe[] = '<cmdl><s>(<m><s><q>wget';
   $g_FlexDBShe[] = 'if(!empty($_FILES[<q>message<q>][<q>name<q>])<s1>AND<s1>(md5($_POST[<q>nick<q>])<s>==<s><q>';
   $g_FlexDBShe[] = 'time()<s>+<s>10000<s>,<s><q>/<q>);<s>echo<s1>$m_zz;<s>eval<s>($m_zz';
   $g_FlexDBShe[] = 'return<s>(<s>strstr<s>(<s>$s<s>,<s>\'echo\'<s>)<s>==<s>false<s>?<s>(<s>strstr<s>(<s>$s<s>,<s>\'print\'';  
   $g_FlexDBShe[] = 'set_time_limit<s>(<s>0<s>);<s>if<s>(!SecretPageHandler::checkKey';
   $g_FlexDBShe[] = '@header("Location:<s><q>.<q>h<q>.<q>t<q>.<q>t<q>.<q>p<q>';
   $g_FlexDBShe[] = '@setcookie(<q>m<q>,<s><q><amc><q>,<s>time()<s>+<s>86400';
   $g_FlexDBShe[] = 'IrSecTeam';
   $g_FlexDBShe[] = '<meta<s1>http-equiv="refresh"<s1>content="<d>;<s>url=<?php';
   $g_FlexDBShe[] = '<meta<s1>http-equiv="Refresh"<s1>content="<d>;<s>URL=http://';
   $g_FlexDBShe[] = '$rBuffLen<s>=<s>ord<s>(<s>VC_Decrypt<s>(<s>fread<s>(<s>$input,<s>1<s>)<s>)<s>)<s>*<s>256';
   $g_FlexDBShe[] = 'clearstatcache(<s>);<s>if<s>(<s>!is_dir<s>(<s>$fld<s>)<s>)<s>return';
   $g_FlexDBShe[] = 'content=<q>no-cache<q>;<s>$config[<q>description<q>]<s>.=<s><q>';
   $g_FlexDBShe[] = 'tmhapbzcerff';
   $g_FlexDBShe[] = '<?php<s1>copy<s>(<s><q>http://';
   $g_FlexDBShe[] = 'file_get_contents<s>(<m><s>ADMIN_REDIR_URL<s>,<s>false<s>,<s>$ctx<s>)';
   $g_FlexDBShe[] = 'echo<s1><q>o.k.<q>;<s>?>';
   $g_FlexDBShe[] = 'move_uploaded_file<s>(<m><s>$_FILES[<s><q>filename<q><s>][<s><q>tmp_name<q><s>]<s>,<s>$_FILES[<s><q>filename<q><s>][<s><q>name<q><s>]';
   $g_FlexDBShe[] = 'echo<s>(<m><s><q>NO FILE<q>';
   $g_FlexDBShe[] = 'if<s>(<s>$i<s><<s>(<s>count<s>(<s>$_POST[<s><q>q<q><s>]<s>)<s>-<s>1';
   $g_FlexDBShe[] = 'isset<s>(<s>$_FILES[<s><q>x<q><s>]<s>)<s>?<s>(<s>is_uploaded_file<s>(<s>$_FILES[<s><q>x<q><s>][<s><q>tmp_name<q><s>]<s>)<s>?<s>(<s>copy<s>(<s>$_FILES[<s><q>x<q><s>]';
   $g_FlexDBShe[] = '$URL<s>=<s>$urls[<s>rand(<s>0<s>,<s>count<s>(<s>$urls<s>)<s>-<s>1<s>)<s>]';
   $g_FlexDBShe[] = '@move_uploaded_file<s>(<s>$_FILES[<s><q>message<q><s>][<s><q>tmp_name<q><s>]<s>,<s>$security_code<s>.<s>"/"<s>.<s>$_FILES[<q>message<q>][<q>name<q>])';
   $g_FlexDBShe[] = 'eval<s>(<m><s>strrev<s>(<m><s>str_replace';
   $g_FlexDBShe[] = 'IO::Socket::INET->new(Proto<s>=><s>"tcp"<s>,<s>LocalPort<s>=><s>36000<s>,<s>Listen<s>=><s>SOMAXCONN';
   $g_FlexDBShe[] = 'RewriteRule<s1>.*<s1>index.php?url=$0<s1>[L,QSA]';
   $g_FlexDBShe[] = '$res=mysql_query(<q>SELECT<s1>*<s1>FROM<s1>`watchdog_old_05`<s1>WHERE<s1>page';
   $g_FlexDBShe[] = '^downloads/([0-9]*)/([0-9]*)/$<s1>downloads.php?c=$1&p=$2';
   $g_FlexDBShe[] = 'preg_replace<s>(<s>$exif[<s>\'Make\'<s>]<s>,<s>$exif[<s>\'Model\'<s>]';
   $g_FlexDBShe[] = 'fclose($f);<s>echo<s>"o.k."';
   $g_FlexDBShe[] = 'function<s1>inject($file,<s>$injection=';
   $g_FlexDBShe[] = 'execl("/bin/sh", "/bin/sh", "-i", 0)';
   $g_FlexDBShe[] = 'find<s1>/<s1>-type<s1>f<s1>-perm<s1>-04000<s1>-ls';
   $g_FlexDBShe[] = 'if<s>(<s>function_exists<s>(<s>\'pcntl_fork';
   $g_FlexDBShe[] = 'urlencode(print_r(array(),1)),5,1).c),$c);}eval($d)';
   $g_FlexDBShe[] = 'array_key_exists<s>(<s>$fileRas<s>,<s>$fileType)<s>?<s>$fileType[<s>$fileRas<s>]';
   $g_FlexDBShe[] = 'if<s>(<s>fwrite<s>(<s>$handle<s>,<s>file_get_contents<s>(<s>$_<gpc>';
   $g_FlexDBShe[] = 'if<s>(<s>$_POST[<s><q>path<q><s>]<s>==<s><q><q><s>)<s>{<s>$uploadfile<s>=<s>$_FILES[<s><q>file<q><s>][<s><q>name<q><s>]';
   $g_FlexDBShe[] = 'str_rot13<s>(<s><q>onfr64_qrpbqr<q>';
   $g_FlexDBShe[] = 'str_rot13<s>(<s><q>tmvasyng<q>';
   $g_FlexDBShe[] = 'if<s>(<s>$dataSize<s><<s>BOTCRYPT_MAX_SIZE<s>)<s>rc4<s>(<s>$data,<s>$cryptkey';
   $g_FlexDBShe[] = ',<s>array<s>(\'.\',\'..\',\'Thumbs.db\')<s>)<s>)<s>{<s>continue;<s>}<s>if<s>(<s>is_file';
   $g_FlexDBShe[] = '$fl<s>=<s>"<meta http-equiv=\"Refresh\"<s1>content=\"0;<s>URL=';
   $g_FlexDBShe[] = ')<s>.<s>substr<s>(<s>md5<s>(<s>strrev<s>(<s>$';
   $g_FlexDBShe[] = 'assert<s>(<s>stripslashes';
   $g_FlexDBShe[] = '<q>/.*/e<q>';
   $g_FlexDBShe[] = '<q>e/*./<q>';
   $g_FlexDBShe[] = 'echo<q><center><b>Done<s>==><s>$userfile_name';
   $g_FlexDBShe[] = 'if<s>($key<s>!=<s><q>mail_to<q><s>&&<s>$key<s>!=<s><q>smtp_server<q><s>&&<s>$key<s>!=<s><q>smtp_port';
   $g_FlexDBShe[] = 'strpos($ua,<s><q>yandexbot<q>)<s>!==<s>false';
   $g_FlexDBShe[] = 'if(CheckIPOperator()<s>&&<s>!isModem())';
   $g_FlexDBShe[] = 'url=<?php<s>echo<s>$rand_url;?>';
   $g_FlexDBShe[] = 'echo<s><q>answer=error<q>';
   $g_FlexDBShe[] = '$post<s>=<s><q>\x77\x67\x65';
   $g_FlexDBShe[] = 'if<s>(detect_mobile_device())<s>{<s>header';
   $g_FlexDBShe[] = 'symbian|midp|wap|phone|pocket';
   $g_FlexDBShe[] = 'Hacked<s1>By';
   $g_FlexDBShe[] = 'IrIsT.Ir';
   $g_FlexDBShe[] = 'function<s>chmod_R<s>(<s>$path<s>,<s>$perm<s>';
   $g_FlexDBShe[] = 'eval<s>(<s>gzinflate<s>(<s>str_rot13';
   $g_FlexDBShe[] = 'eval<s>(<s>str_rot13';
   $g_FlexDBShe[] = '$letter<s>=<s>str_replace<s>(<s>$ARRAY[0][$j]<s>,<s>$arr[$ind]<s>,<s>$letter';
   $g_FlexDBShe[] = 'create_function<s>(<s><q>$m<q><s>,<s><q>if<s>(<s>$m<s>[<s>0x01<s>]<s>==<s>"L"';
   $g_FlexDBShe[] = '$p<s>=<s>strpos($tx<s>,<s><q>{#<q><s>,<s>$p2<s>+<s>2)';
   $g_FlexDBShe[] = '$user_agent<s>=<s>preg_replace<s>(<s><q>|User\.Agent\:[\s ]?|i<q><s>,<s><q><q><s>,<s>$user_agent';
   $g_FlexDBShe[] = 'print("#<s1>info<s1>OK\n\n")';
   $g_FlexDBShe[] = ']<s>}<s>=<s>trim<s>(<s>array_pop<s>(<s>${<s>${';
   $g_FlexDBShe[] = ']=<q>ip<q><s>;<s>if<s>(<s>isset<s>(<s>$_SERVER[';
   $g_FlexDBShe[] = 'print<s>$sock "PRIVMSG ".$owner';
   $g_FlexDBShe[] = 'if(/^\:$owner!.*\@.*PRIVMSG.*:.msgflood(.*)/){';
   $g_FlexDBShe[] = '[-]<s1>Connection<s1>faild';
   $g_FlexDBShe[] = 'phpinfo();';
   $g_FlexDBShe[] = '<!--#exec<s1>cmd=<q>$HTTP_ACCEPT<q><s>-->';
   $g_FlexDBShe[] = '<q>From:<s><q>.$_POST[<q>realname<q>].<q> <q>.<q> <<q>.$_POST[<q>from<q>].<q>>\n<q>';
   $g_FlexDBShe[] = 'if<s>(<s>is_dir<s>(<s>$FullPath<s>)<s>)<s>AllDir<s>(<s>$FullPath<s>,<s>$Files<s>);<s>}<s>}';
   $g_FlexDBShe[] = 'google|yandex|bot|rambler';
   $g_FlexDBShe[] = 'RewriteCond<s>%{HTTP_USER_AGENT}<s>.*ndroid.*';
   $g_FlexDBShe[] = '(msie|opera)';
   $g_FlexDBShe[] = '<h1>Loading...</h1>';
   $g_FlexDBShe[] = 'ErrorDocument<s1>500<s1>http://';
   $g_FlexDBShe[] = 'ErrorDocument<s1>400<s1>http://';
   $g_FlexDBShe[] = '$p<s>=<s>strpos<s>(<s>$tx<s>,<s><q>{#<q><s>,<s>$p2<s>+<s>2)';
   $g_FlexDBShe[] = '<script<s1>language=<q><m>JavaScript<q><m>><s>parent.window.opener.location<s>=<s><q><m>http://';
   $g_FlexDBShe[] = 'preg_match_all(<q>/<a href="\/url\?q=(.+?)[&|"]+/is<q>, $page[<q>exe<q>], $links)';
   $g_FlexDBShe[] = '$url<s>=<s>$url<s>.<s><q>?<q><s>.<s>http_build_query($query)';
   $g_FlexDBShe[] = 'print<s1>$sock<s1><q>NICK <q><s1>.<s1>$nick<s1>.<s1><q>\n<q>';
   $g_FlexDBShe[] = 'PRIVMSG.*:.owner\s+(.*)';
   $g_FlexDBShe[] = 'echo<s1>stripslashes<s>(<s>$_<gpc>[';
   $g_FlexDBShe[] = '/usr/sbin/httpd';
   $g_FlexDBShe[] = '$resultFUL<s>=<s>stripcslashes<s>(<s>$_POST[<q>resultFUL<q>';
   $g_FlexDBShe[] = '=<s>$GLOBALS[<s><q>_<gpc><q><s>]';
   $g_FlexDBShe[] = '$_<gpc>[<q><amc><q>](<s>$_<gpc>[<q><amc><q>]<s>)';
   $g_FlexDBShe[] = 'preg_replace<s>(<s><q>/.*/';
   $g_FlexDBShe[] = 'chr<s>(<s>101<s>)<s>.<s>chr<s>(<s>118<s>)<s>.<s>chr<s>(<s>97<s>)<s>.<s>chr<s>(<s>108<s>)';
   $g_FlexDBShe[] = '$auth_pass<s>=';
   $g_FlexDBShe[] = 'if<s>(<s>@<m>md5<s>(<s>$_<gpc>[';
   $g_FlexDBShe[] = '$mailer<s>=<s>$_POST[<s><q>x_mailer<q><s>]';
   $g_FlexDBShe[] = 'echo<s1>file_get_contents<s>(<s>base64_url_decode<s>(<s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'preg_replace<s>(<s>@<m>$_<gpc>';
   $g_FlexDBShe[] = 'fwrite<s>(<s>$fh<s>,<s>stripslashes<s>(<s>@<m>$_<gpc>[';
   $g_FlexDBShe[] = 'if<s>(<s>mail<s>(<s>$mails[$i]<s>,<s>$tema<s>,<s>base64_encode<s>(<s>$text';
   $g_FlexDBShe[] = '$gzip<s>=<s>@<m>gzinflate<s>(<s>@<m>substr<s>(<s>$gzencode_arg';
   $g_FlexDBShe[] = 'move_uploaded_file($_FILES[<q>elif<q>][<q>tmp_name';
   $g_FlexDBShe[] = 'killall<s1>-9';
   $g_FlexDBShe[] = 'curl.haxx.se/rfc/cookie_spec';
   $g_FlexDBShe[] = 'CVV:<s>$cv';
   $g_FlexDBShe[] = 'header(<q>s:<s><q><s>.<s>php_uname<s>(<s><q>n<q><s>)';
   $g_FlexDBShe[] = 'By<s1>WebRooT';
   $g_FlexDBShe[] = '$OOO0O0O00=__FILE__;<s>$OO00O0000<s>=<s>0x1b540;<s>eval';
   $g_FlexDBShe[] = '$mailer<s>=<s>$_POST[<q>x_mailer<q>]';
   $g_FlexDBShe[] = 'preg_match(<q>/(yandex|google|bot)/i<q>,<s>getenv(<q>HTTP_USER_AGENT<q>)))';
   $g_FlexDBShe[] = 'echo<s1>$ifupload=<q><s>ItsOk<s><q>';
   $g_FlexDBShe[] = 'fsockopen<s>(<s>$ConnectAddress<s>,<s>25';
   $g_FlexDBShe[] = '$_SESSION[<q>session_pin<q>]<s>=<s><q>$PIN';
   $g_FlexDBShe[] = '$url<q><s>.<s>$session_id<s>.<s><q>/login.html';
   $g_FlexDBShe[] = 'content=<q>1;URL=cgi-bin.html?cmd';
   $g_FlexDBShe[] = 'f<s>=<s>$q<s>.<s>$a<s>.<s>$b<s>.<s>$x';
   $g_FlexDBShe[] = 'if<s>(md5(trim($_<gpc>[';
   $g_FlexDBShe[] = 'die<s>(<s>PHP_OS<s>.<s>chr<s>(';
   $g_FlexDBShe[] = 'CURLOPT_REFERER,<s><q>https://www.google.co';
   $g_FlexDBShe[] = 'echo<s1><q>install_ok<q>';
   $g_FlexDBShe[] = '<qq>eval<qq>';
   $g_FlexDBShe[] = '<qq>base64_decode<qq>';
   $g_FlexDBShe[] = '<qq>create_function<qq>';
   $g_FlexDBShe[] = '<qq>assert<qq>';
   $g_FlexDBShe[] = 'create_function<s>(<q><q><s>,<s>str_rot13';
   $g_FlexDBShe[] = '$headers<s>=<s>$_<gpc>[<q>headers<q>]';
   $g_FlexDBShe[] = 'file_put_contents<s>(<q>1.txt<q><s>,<s>print_r<s>(<s>$_POST<s>,<s>true';
   $g_FlexDBShe[] = 'echo<s1><q>good<q>';
   $g_FlexDBShe[] = 'echo<s1><q>ok<q>';
   $g_FlexDBShe[] = 'Spam<s1>completed';
   $g_FlexDBShe[] = 'fwrite<s>(<s>$flw<s>,<s>$fl<s>)';
   $g_FlexDBShe[] = 'eval<s>(<s>get_option';
   $g_FlexDBShe[] = '$sys_params<s>=<s>@<m>file_get_contents';
   $g_FlexDBShe[] = 'Joomla_brute_Force';
   $g_FlexDBShe[] = '$allemails<s>=<s>@split("\n"<s>,<s>$emaillist)';
   $g_FlexDBShe[] = 'RewriteCond<s>%{HTTP:x-wap-profile';
   $g_FlexDBShe[] = 'RewriteCond<s>%{HTTP:x-operamini-phone-ua}';

   print '$g_FlexDBShe = unserialize(base64_decode("' . base64_encode(serialize(array_reverse(covertMeta($g_FlexDBShe)))) . '"));<br>' . "\n";
 
  $g_ExceptFlex[] = 'sort()';
  $g_ExceptFlex[] = 'must-reval';
  $g_ExceptFlex[] = 'retrieval';
  $g_ExceptFlex[] = 'doubleval';
  $g_ExceptFlex[] = 'require<s>(<m><s>$_SERVER[<s><q>DOCUMENT_ROOT<q><s>]';
  $g_ExceptFlex[] = 'require_once<s>(<m><s>$_SERVER[<s><q>DOCUMENT_ROOT<q><s>]';
  $g_ExceptFlex[] = 'include<s>(<m><s>$_SERVER[<s><q>DOCUMENT_ROOT<q><s>]';
  $g_ExceptFlex[] = 'include_once<s>(<m><s>$_SERVER[<s><q>DOCUMENT_ROOT<q><s>]';
  $g_ExceptFlex[] = '$smarty->_eval(';
  $g_ExceptFlex[] = 'prep<s1>rm<s1>-rf<s1>%{buildroot}';
  $g_ExceptFlex[] = 'TODO:<s1>rm<s1>-rf<s1>the';
  $g_ExceptFlex[] = 'krsort($wpsmiliestrans);';
  $g_ExceptFlex[] = 'document.write(unescape("%3Cscript src=\'" + gaJsHost + "go';
  $g_ExceptFlex[] = '.exec';
  $g_ExceptFlex[] = 'exec()';      
  $g_ExceptFlex[] = '$x1 = $this->w - $x1;';
  $g_ExceptFlex[] = 'asort($CacheDirOldFilesAge);';
  $g_ExceptFlex[] = '(\'r57shell\',';
  $g_ExceptFlex[] = 'eval("listener = "+list';
  $g_ExceptFlex[] = 'eval()';
  $g_ExceptFlex[] = 'preg_replace_callback(\'/\{(ima';
  $g_ExceptFlex[] = 'eval (_ctMenuInitStr';
  $g_ExceptFlex[] = 'base64_decode($accountKey)';
  $g_ExceptFlex[] = 'base64_decode($data)); $api->setRe';
  $g_ExceptFlex[] = 'require($_SERVER[\"DOCUMENT_ROOT\"].\"/b';
  $g_ExceptFlex[] = 'base64_decode($_REQUEST[\'parameters\']); if(CheckSerializedD';
  $g_ExceptFlex[] = 'pcntl_exec\' => Array(Array(1), $arResult[\'SECURING_FUNCTIO';
  $g_ExceptFlex[] = 'echo "<script>alert(\'".CUtil::JSEscap';
  $g_ExceptFlex[] = 'base64_decode($_REQUEST[\'title_changer_link\']); if (strlen($';
  $g_ExceptFlex[] = 'eval(\'$hexdtime = "\' . $hexdtime . \'";\'); $f';
  $g_ExceptFlex[] = 'echo "<script>alert(\'$row->title - "._MODULE_IS_E';
  $g_ExceptFlex[] = 'echo "<script>alert(\'$cids "._CANN';
  $g_ExceptFlex[] = 'if(1) { $v_hour = ($p_header[\'mtime';
  $g_ExceptFlex[] = 'document.write(unescape("%3Cscript%20src=%22http" + (("https:" =';
  $g_ExceptFlex[] = 'document.write(unescape("%3Cscript src=\'" + pkBaseURL';
  $g_ExceptFlex[] = 'echo "<script>alert(\'".JText::';
  $g_ExceptFlex[] = "'filename'), ('r57shell";
  $g_ExceptFlex[] = 'echo "<script>alert(\'" . $errMsg . "\')';
  $g_ExceptFlex[] = 'echo "<script>alert(\"Error when loading';
  $g_ExceptFlex[] = 'echo "<script>alert(\'".JText::_(\'VALID_E';
  $g_ExceptFlex[] = 'eval()';
  $g_ExceptFlex[] = '\'system\'';
  $g_ExceptFlex[] = '\'eval\'';
  $g_ExceptFlex[] = '"eval"';
  $g_ExceptFlex[] = 'copy(';
  $g_ExceptFlex[] = '_system';
  $g_ExceptFlex[] = 'save2copy';
  $g_ExceptFlex[] = 'filesystem';
  $g_ExceptFlex[] = 'sendmail';
  $g_ExceptFlex[] = 'canChmod';
  $g_ExceptFlex[] = 'doubleval';
  $g_ExceptFlex[] = 'operating system';
  $g_ExceptFlex[] = 'globaleval';
  $g_ExceptFlex[] = 'with 0/0/0 if (1) {';
  $g_ExceptFlex[] = '$x2 = $param[<q>x<q>] + $width';
  $g_ExceptFlex[] = 'specialised';
  $g_ExceptFlex[] = 'wp_get_current_user';
  $g_ExceptFlex[] = '->chmod';
  $g_ExceptFlex[] = '_mail(';
  $g_ExceptFlex[] = '_copy(';
  $g_ExceptFlex[] = 'strpos($_SERVER[\'HTTP_USER_AGENT\'], \'Drupa';
  $g_ExceptFlex[] = 'strpos($_SERVER[\'HTTP_USER_AGENT\'], \'MSIE';
  $g_ExceptFlex[] = 'strpos($_SERVER["HTTP_USER_AGENT"], \'MSIE';
  $g_ExceptFlex[] = 'eval (classStr)';
  $g_ExceptFlex[] = 'function_exists(\'base64_decode';
  $g_ExceptFlex[] = '"assert","count"';
  $g_ExceptFlex[] = '"reposition","assert"';
  $g_ExceptFlex[] = '\'assert\', \'assert';
  $g_ExceptFlex[] = 'echo "<script>alert(\'".JText::_(\'VALID_EM';
  $g_ExceptFlex[] = '\'base64_decode\')) { $value = base64_encode(serialize($v';

  print '$g_ExceptFlex = unserialize(base64_decode("' . base64_encode(serialize(covertMeta($g_ExceptFlex))) . '"));<br>' . "\n";

//  print "<hr><pre>";
//  var_dump($g_FlexDBShe);
//  var_dump(array_reverse($g_DBShe));
//  print "\n";
  
  $g_SusDB[] = 'Spammer';
  $g_SusDB[] = 'ini_get<s>(<m><q>safe_mode<q>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'eval<s><fun>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'assert<s><fun>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'srpath://../../../..';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'phpinfo<s>(';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'SHOW<s1>DATABASES';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '<z>popen<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'exec<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>system<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>passthru<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>proc_open<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'shell_exec<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'ini_restore<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>dl<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>symlink<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>chgrp<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>ini_set<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>putenv<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'getmyuid<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'fsockopen<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'posix_setuid<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'posix_setsid<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'posix_setpgid<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'posix_kill<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'apache_child_terminate<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>chmod<s>(';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '<z>chdir<s>(';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'pcntl_exec<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>virtual<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'proc_close<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'proc_get_status<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'proc_terminate<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'proc_nice<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'getmygid<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'proc_getstatus<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'proc_close<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'escapeshellcmd<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'escapeshellarg<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'show_source<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>pclose<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'safe_dir<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'ini_restore<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'chown<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'chgrp<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'shown_source<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'mysql_list_dbs<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'get_current_user<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'getmyid<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>leak<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'pfsockopen<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'get_current_user<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'syslog<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '$default_use_ajax';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'eval<s>(<m><s>unescape';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'FLoodeR';
  $g_SusDB[] = 'document.write<s>(<s>unescape';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<z>copy<s>(';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'move_uploaded_file<s>(';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '.333333';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '.666666';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'round<s>(<m><s>0<s>)<m>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'copy<s>(<m><s>$_FILES<s>[<s><q>file<q><s>][<s><q>tmp_name<q><s>]<s>,<s>$uploadfile';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'move_uploaded_files<s>(<m><s>$_FILES<s>[<s><q>file<q><s>][<s><q>tmp_name<q><s>]<s>,<s>$uploadfile';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'ini_get<s>(<s><q>disable_functions<q>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'UNION<s1>SELECT<s1><q>0<q>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '2<s>><s>&1';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'echo<s>(<m><s>$_SERVER[<q>DOCUMENT_ROOT<q>]';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = '=<s>Array<s>(<m><s>base64_decode<s>(<m>';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'killall<s1>-<d>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'eriuqer';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'touch<s>(';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'sshkeys';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '@include';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '@require';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '@ini_set<s>(<m><q>allow_url_fopen';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '@file_get_contents';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = 'file_put_contents';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'android<s>|<s>midp<s>|<s>j2me<s>|<s>symbian';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '@setcookie<s>(<m><q>hit';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = '@fileowner';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = '<kuku>';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'sypex';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = '$beecode';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'Backdoor';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'php_uname<s>(';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'mail<s>(<m><s>$to<s>,<s>$subj<s>,<s>$msg<s>,<s>$from';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'mail<s>(<m><s>$send<s>,<s>$subject<s>,<s>$headers<s>,<s>$message';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'mail<s>(<m><s>$to<s>,<s>$subject<s>,<s>$message<s>,<s>$headers';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'strpos<s>(<m><s>$name<s>,<s><q>HTTP_<q><s>)<m><s>!==<s>0<s>&&<s>strpos<s>(<m><s>$name<s>,<s><q>REQUEST_';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'is_function_enabled<s>(<s><m><q>ignore_user_abort';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'echo<s>(<m><s>file_get_contents';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'echo<s>(<m><q><script';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'print<s>(<m><s>file_get_contents';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'print<s>(<m><q><script';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = '<marquee<s1>style<s>=<s><q>position<s>:<s>absolute<s>;<s>width<s>:<s><d><s>px<s>';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = '=<s><q>../../../wp-config.php';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'eggdrop';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'rwxrwxrwx';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = 'error_reporting';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = '<z>create_function';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '{<s>position<s>:<s>absolute;<s>left<s>:<s>-';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = '<script<s1>async';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = '_<q><s>]<s>=<s>Array<s>(<s>base64_decode<s>(<m><s><q>';	$g_SusDBPrio[] = 2;
  $g_SusDB[] = 'AddType<s1>application/x-httpd-cgi';	$g_SusDBPrio[] = 0;
  $g_SusDB[] = 'getenv<s>(<m><s><q>HTTP_COOKIE<q>';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = 'ignore_user_abort<s>(<m><s><q><m>1<q>';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '$_REQUEST<s>[<s>%22';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = 'url<s>(<q>data<s>:<s>image/png;<s>base64<s>,';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = 'url<s>(<q>data<s>:<s>image/gif;<s>base64<s>,';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = ':<s>url<s>(<s><q><?php';	$g_SusDBPrio[] = 3;
  $g_SusDB[] = '</html><a><script';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '</html><a><iframe';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '<cmdl><s><fun>';	$g_SusDBPrio[] = 1;
  $g_SusDB[] = '<z>mail<s>(';	$g_SusDBPrio[] = 4;
  $g_SusDB[] = 'file_get_contents<s>(<m><s><q>php://input'; $g_SusDBPrio[] = 1;
  $g_SusDB[] = '<meta<s1>http-equiv=<q>Content-type<q><s1>content=<q>text/html;<s>charset=windows-1251<q>><body>';  $g_SusDBPrio[] = 3;
  $g_SusDB[] = '=<s>document.createElement(<s><q>script<q><s>);';

//  $g_SusDB[] = 'if<s>(<s><d><s>)<s>{';

  print '$g_SusDB = unserialize(base64_decode("' . base64_encode(serialize(covertMeta($g_SusDB))) . '"));<br>' . "\n";
  print '$g_SusDBPrio = unserialize(base64_decode("' . base64_encode(serialize($g_SusDBPrio)) . '"));<br>' . "\n";

  $g_AdwareSig[] = '__linkfeed_robots__';
  $g_AdwareSig[] = 'LINKFEED_USER';
  $g_AdwareSig[] = '__sape_delimiter__';
  $g_AdwareSig[] = 'dispenser.articles.sape.ru';
  $g_AdwareSig[] = 'LENK_client';
  $g_AdwareSig[] = 'SAPE_client';
  $g_AdwareSig[] = 'SLArticlesClient';
  $g_AdwareSig[] = '->GetLinks<s>()';
  $g_AdwareSig[] = 'db.trustlink.ru';
  $g_AdwareSig[] = 'class<s1>CM_client<s1>extends<s>CM_base';
  $g_AdwareSig[] = 'new<s1>CM_client()';
  $g_AdwareSig[] = 'tl_links_db_file';
  $g_AdwareSig[] = 'TrustlinkClient';
  $g_AdwareSig[] = '-><s>SLClient';
  $g_AdwareSig[] = 'isset<s>(<m><s>$_SERVER<s>[<s><q>HTTP_USER_AGENT<q><s>]<s>)<s>&&<s>(<m><s>$_SERVER<s>[<s><q>HTTP_USER_AGENT<q>]<s>==<s><q>LMP_Robot';
  $g_AdwareSig[] = '$links-><s>return_links<s>(<m><s>$lib_path';
  $g_AdwareSig[] = '$links_class<s>=<s>new<s1>Get_links<s>(<m><s>';
  $g_AdwareSig[] = '<q><s>,<s><q>.<q><s>)<m><s>;<s>?>';
  $g_AdwareSig[] = 'levitra';
  $g_AdwareSig[] = 'dapoxetine';
  $g_AdwareSig[] = 'viagra';
  $g_AdwareSig[] = 'cialis';
  $g_AdwareSig[] = 'provigil';
  $g_AdwareSig[] = 'class<s1>TWeffClient';
  $g_AdwareSig[] = 'new<s1>SLClient()';
  $g_AdwareSig[] = '__linkfeed_before_text__';
  $g_AdwareSig[] = '__test_tl_link__';

  print '$g_AdwareSig = unserialize(base64_decode("' . base64_encode(serialize(covertMeta($g_AdwareSig))) . '"));<br>' . "\n";

  $g_JSVir[] = "f='f'+'r'+'o'+'m'+'Ch'+'arC'+'ode';";
  $g_JSVir[] = '.prototype.a}catch(';
  $g_JSVir[] = 'try{Boolean().prototype.q}catch(';
  $g_JSVir[] = "if(Ref.indexOf('.google.')!=";
  $g_JSVir[] = 'indexOf|if|rc|length|msn|yahoo|referrer|altavista|ogo|bi|hp|var|aol|query';
  $g_JSVir[] = 'Array.prototype.slice.call(arguments).join("")';
  $g_JSVir[] = 'q=document.createElement("d"+"i"+"v");q.appendChild(q+"");}catch(qw){h=';
  $g_JSVir[] = '+zz;ss=[];f=\'fr\'+\'om\'+\'Ch\';f+=\'arC\';f+=\'ode\';w=this;e=w[f["substr"](';
  $g_JSVir[] = 's5(q5){return ++q5;}function yf(sf,we){return sf.substr(we,1);}function y1(wb){if(wb==168)wb=1025;else';
  $g_JSVir[] = 'if(navigator.userAgent.match(/(android|midp|j2me|symbian';
  $g_JSVir[] = 'document.write(\'<script language="JavaScript" type="text/javascript" src="\'+domain+\'"></scr\'+\'ipt>\')';
  $g_JSVir[] = 'http://phsp.ru/_/go.php?sid=';
  $g_JSVir[] = '</html><s><script';
  $g_JSVir[] = '</html><s><iframe';
  $g_JSVir[] = '=navigator[appVersion_var].indexOf("MSIE")!=-1?\'<iframe name';
  $g_JSVir[] = "\\x65At"; 
  $g_JSVir[] = "\\x61rCod"; 
  $g_JSVir[] = "\"fr\"+\"omC\"+\"harCode\"";
  $g_JSVir[] = "=\"ev\"+\"al\""; "fr\\x6fmChar"; "\\x43";
  $g_JSVir[] = "[((e)?\"s\":\"\")+\"p\"+\"lit\"](\"a$\"[((e)?\"su\":\"\")+\"bstr\"](1));";
  $g_JSVir[] = "f='fr'+'om'+'Ch';f+='arC';f+='ode';";
  $g_JSVir[] = "f+=(h)?'ode':\"\";";
  $g_JSVir[] = "f='f'+'r'+'o'+'m'+'Ch'+'arC'+'ode';";
  $g_JSVir[] = "f='fromCh';f+='arC';f+='qgode'[\"substr\"](2);";
  $g_JSVir[] = "var<s1>div_colors";
  $g_JSVir[] = "var<s1>_0x";
  $g_JSVir[] = "CoreLibrariesHandler";
  $g_JSVir[] = "pingnow";
  $g_JSVir[] = "serchbot";
  $g_JSVir[] = "km0ae9gr6m";
  $g_JSVir[] = "c3284d";
  $g_JSVir[] = "\\x68arC";
  $g_JSVir[] = "\\x6dCha"; 
  $g_JSVir[] = "\\x6fde";
  $g_JSVir[] = "\\x6fde"; 
  $g_JSVir[] = "\\x43ode"; 
  $g_JSVir[] = "\\x72om";
  $g_JSVir[] = "\\x43ha"; 
  $g_JSVir[] = "\\x72Co"; 
  $g_JSVir[] = "\\x43ode";
  $g_JSVir[] = '.dyndns.';
  $g_JSVir[] = '.dyndns-';
  $g_JSVir[] = '}<s>else<s>{<s>document.write<s>(<s><q>.<q>)<s>}<s>}<s>R(<s>)';
  $g_JSVir[] = 'document.write(unescape(\'%3Cdiv%20id%3D%22';
  $g_JSVir[] = '.bitcoinplus.com';
  $g_JSVir[] = '.split("&&");h=2;s="";if(m)for(i=0;';
  $g_JSVir[] = 'document.write<s>(<s>unescape<s>(<q>%3c';
  $g_JSVir[] = '<iframe<s1>src="http://deluxesclicks.pro/';
  $g_JSVir[] = '3Bfor|fromCharCode|2C27|3D|2C88|unescape';
  $g_JSVir[] = ';<s>document.write(<q><iframe<s>src="http://ya.ru';
  $g_JSVir[] = 'w.document.body.appendChild(script);<s>clearInterval(i);<s>}<s>}<s>,<s><d><s>)<s>;<s>}<s>)(<s>window';
  $g_JSVir[] = 'if(!g()&&window.navigator.cookieEnabled){document.cookie="1=1;expires="+e.toGMTString()+";path=/";';
  $g_JSVir[] = 'nn_param_preloader_container|5001|hidden|innerHTML|inject|visible';
  $g_JSVir[] = '<!-- <amc>||stat -->';
  $g_JSVir[] = '&parameter=$keyword&se=$se&ur=1&HTTP_REFERER=\'+encodeURIComponent(document.URL)';
  $g_JSVir[] = 'windows|series|60|symbos|ce|mobile|symbian';
  $g_JSVir[] = '["eval"](s);}}}}</script>';
  $g_JSVir[] = 'kC70FMblyJkFWZodCKl1WYOdWYUlnQzRnbl1WZsVEdldmL05WZtV3YvRGI9';
  $g_JSVir[] = '{k=i;s=s.concat(ss(eval(asq())-1));}z=s;eval(';
  $g_JSVir[] = 'document.cookie.match(new<s1>RegExp(<s>"(?:^|; )"<s>+<s>name.replace(/([\.$?*|{}\(\)\[\]\\/\+^])/g';
  $g_JSVir[] = 'setCookie<s>(<m><s>"arx_tt"<s>,<s>1<s>,<s>dt.toGMTString()<s>,<s><q>/<q>';
  $g_JSVir[] = '/*214afaae*/';
  $g_JSVir[] = 'document.cookie.match<s>(<s>new<s1>RegExp<s>(<s>"(?:^|;<s>)"<s>+<s>name.replace<s>(/([\.$?*|{}\(\)\[\]\\/\+^])/g';
  $g_JSVir[] = 'var<s1>dt<s1>=<s1>new<s1>Date(),<s1>expiryTime<s1>=<s1>dt.setTime(<s1>dt.getTime()<s1>+<s1>900000000';
  $g_JSVir[] = 'if<s>(<s>num<s>===<s>0<s>)<s>{<s>return<s>1;<s>}<s>else<s>{<s>return<s1>num<s>*<s>rFact(<s>num<s>-<s>1';
  $g_JSVir[] = '+=String.fromCharCode(parseInt(0+\'x\'';
  $g_JSVir[] = '<script<s1>language="JavaScript"><s>parent.window.opener.location="http://vk.com';
  $g_JSVir[] = 'location.replace(<q>http://v5k45.ru';
  $g_JSVir[] = ';try{++document.body}catch(q){aa=function(ff){for(i=0;i<z.length;i++){za+=String[ff](e(v+(z[i]))-12);}};}';
  $g_JSVir[] = 'document.write<s>(<q><<q><s>+<s>x[0]<s>+<s><q> <q><s>+<s>x[4]<s>+<s><q>>.<q><s>+x<s>[2]<s>+';
  $g_JSVir[] = 'if(t.length==2){z+=String.fromCharCode(parseInt(t)+';
  $g_JSVir[] = 'window.onload<s>=<s>function()<s>{<s>if<s>(document.cookie.indexOf(';
  $g_JSVir[] = 'document.getElementsByTagName(<q>head<q>)[0].appendChild(a)';
  $g_JSVir[] = '.style.height<s>=<s><q>0px<q>;window.onload<s>=<s>function()<s>{document.cookie';
  $g_JSVir[] = '.src=(<q>htps:<q>==document.location.protocol?<q>https://ssl<q>:<q>http://<q>)+';
  $g_JSVir[] = '404.php<q>><s></script>';
  $g_JSVir[] = 'preg_match(<q>/sape/i<q><s>,<s>$_SERVER[<q>HTTP_REFERER';
  $g_JSVir[] = 'ip(hone|od)|iris|kindle';

  $g_JSVir[] = '-<s>PayPal<s></title>';
  $g_JSVir[] = '-<s>Privati<s></title>';
  $g_JSVir[] = '<title><s>UniCredit';

  $g_JSVir[] = '{position:absolute;top:-9999px;}</style><div<s1>class=';
  $g_JSVir[] = 'if<s>((ua.indexOf(<q>chrome<q>)<s>==<s>-1<s>&&<s>ua.indexOf("win")<s>!=<s>-1)<s>&&<s>navigator.javaEnabled';
  $g_JSVir[] = 'parent.window.opener.location=<q>http://vk.com.';

  $g_JSVir[] = 'sexfromindia.com';

  print '$g_JSVirSig = unserialize(base64_decode("' . base64_encode(serialize(covertMeta($g_JSVir))) . '"));<br>' . "\n";

?>